### ISSUE TITLE
Question - Nicotine Still Being Developed?

### ISSUE THREAD

**Issue by ghost** [Nicotine-Plus/nicotine-plus#1]
Hi,

Welcome to GItHub... :)

Is Nicotine still being developed because I haven't seen any new versions for serveral years, and then I see the project moved to GitHub and it made me wonder, is it still alive?

Please don't let this DIE!

**Comment by alekksander** [comment]
yes, i am also regularly checking for newer versions, but since many years it appears dead. hopefully someone will pick it up one day. luckily, there is multi—platform SoulseekQt  application.

**Comment by alekksander** [comment]
still full of hope :)

**Comment by gfarmerfr** [comment]
@ghost @alekksander

Hi everyone.
I have decided to spend some time improving my python skills by hacking on n+.
@eLvErDe has given me commit rights and i'm cleaning lots of invalid bugs on the old Trac.

My goal is:
- Cleaning up the code base (removing old dependencies or trying alternatives).
- Writing docs.
- Fixing bugs & merge distributions patches.
- Switching to python virtualenv (mostly working on git master).
- Switching to python 3 + GTK 3 if possible.
- Probing the community to see if we need to maintain Windows ans OSX support (I'm on Fedora).
- Reaching out for translations.
- Poking downstream distribution packagers for a heads up when we will do a new release (no timeline at this time).

Every bit of help will be greatly appreciated on any speciality (docs, translation, code, arts, ...).

**Comment by bernd-wechner** [comment]
Awesome Michael! I'm glad to hear it. I wish I had time for same. But 
what little time i have I'm giving to Quod Libet right now.Do keep us 
posted re: progress. I'm back on the SoulSeekQT client for now myself 
for one main reason (it lets me collapse searches to folder level and 
has better support for folder focussed rather than file focussed sharing)

Regards,

Bernd.

Michael Labouebe wrote:

**Comment by gfarmerfr** [comment]
@bernd-wechner  Quod Libet ? Nice ! :)
Do you work on mutagen too (since it branch out of it if my memory serves me) ?
Our previous dev had switch from a internal mp3 metadata handling system to mutagen.
I think it was a good decision since it seems to be well maintain.

" I'm back on the SoulSeekQT client for now myself for one main reason  (it lets me collapse searches to folder level and has better support for folder focussed rather than file focussed sharing)"
=> maybe if you have a few minutes you can do a screenshot of it and open a bug report explaining what's nice about it ? :) I may have a look at it.

**Comment by bernd-wechner** [comment]
OK, filed an issue for you: #17 

Not working actively on mutagen no, nor on quodlibet yet, just set up to. I'm dearly time poor, and it's on my list to work on quodlibet some time as I have some todos there. Helping out with the python3 upgrade might be a start ...

> what's nice about it ?

Well, as a rule, when sharing music say, most of us both store albums one to a folder, and when looking for music are looking for an album, which the sharing party typically has a s folder of songs. The list of songs is an obscuring detail that blows search results out in length and makes it hard to find what you're after ...
