### ISSUE TITLE
Feature Request: Web Interface

### ISSUE THREAD

**Issue by tandy-1000** [Nicotine-Plus/nicotine-plus#1347]
Something similar to Qbittorrent / Deluge's web interface, top priority could be search / download / upload management?

This would allow Nicotine+ to be ran on headless servers without using a VNC setup.

**Comment by mathiascode** [comment]
Due to our highly limited manpower (only me developing in my free time nowadays), and the number of things to take care of already, I think we're better off focusing on improving our existing GUI. I recommend looking into https://github.com/slskd/slskd / https://github.com/jpdillingham/Soulseek.NET for a promising headless client in active development.
