### ISSUE TITLE
Reopen closed tabs

### ISSUE THREAD

**Issue by janekc** [nicotine-plus/nicotine-plus#1424]
Would be nice to have an reopen feature, which brings back a recently closed search tab. On most current browsers this is achieved with pressing `CRTL + SHIFT + T`.

When pressed again, it could bring back tabs in chronical order last in first out.

**Comment by slook** [comment]
The Search History drop-down list already provides useful functionality. Recalling recent Search's is trivial, unless you have done a large number searches and tabs were open for a long time before you closed them.

Remembering more than one recently closed tabs in chronological order would involve an entirely new implementation that would be difficult for the devs to implement cleanly.

May I suggest perhaps instead the Search History list could be expanded to hold a larger number of items, would that be helpful do you think?

**Comment by slook** [comment]
I suppose in theory @mathiascode , since the Search History list is stored in chronological order, it might be possible to implement the OP's desired functionality by iterating the list until the first item is reached that isn't open in a tab, and then creating a new tab for that entry. 

Whilst this might not be accurate in all cases, it might serve the purpose satisfactorily, and this could actually be a useful feature. 

A menu item for 'Reopen Closed Tab' could be added in the Notebook context menu next to 'Close All Tabs' (and instead of 'Clear All Results' which serves no useful purpose), in addition to the Ctrl+Shift+T shortcut suggested by the OP.

**Comment by slook** [comment]
No you're not wrong, but surely it would be very heavy to store and recall the results from disk, and I suppose the Filter settings, sort order and everything. I would think it would be satisfactory enough to create a similar tab with the same search term.
