### ISSUE TITLE
Leech Detector settings

### ISSUE THREAD

**Issue by 82d** [nicotine-plus/nicotine-plus#1455]
it would be a good idea to make the program track not only empty files, but also with a certain number and type of files.
for example, notify about the absence of flac, wav, or aif.
where you can choose. by checking the box in the plugin settings. and the line where to enter the total file size to which this message will be sent.

**Comment by mathiascode** [comment]
Checking a configurable number of files or shared folders is easily doable. Anything other than that will require downloading and parsing full user share responses, which can take up to 30-60 seconds depending on the connection speed and number of shared files. There is also the risk of potential performance issues. I'm concerned about negatively impacting the Soulseek network, so anything related to file size or file type I probably wouldn't accept in a default plugin.

**Comment by 82d** [comment]
I think that you are right. unfortunately, this will affect performance.
how about ctrl+z. this small chip is often not enough.
and also copying ctrl+c is only the name. in 95% of cases, you only need a copy of the directory or the file name. the link has to be cut off every time. it is better to leave copying the link in the menu.

**Comment by mathiascode** [comment]
> how about ctrl+z. this small chip is often not enough.
> and also copying ctrl+c is only the name. in 95% of cases, you only need a copy of the directory or the file name. the link has to be cut off every time. it is better to leave copying the link in the menu.

I've been meaning to look into implementing/fixing these, but this will have to wait for future release. Nicotine+ 3.1.0 is already becoming a huge release. I had a somewhat functional implementation of Ctrl-Z, but there were still some issues to fix.

**Comment by woollarding** [comment]
the leech detector no longer shows the private message sent to users sharing 0 files, making it take more steps and hence longer to ban leechers, enabling them to ...leech more easily?.. i was hoping it would be updated to flash like other notifications at least that would give me a head start (assuming i am looking at the nicotine window),,,maybe its because i don't understand the code, but it seems like there should be a simple way to make an option to auto-ban or somehow give the users that are sharing the option to prevent users who are not contributing from taking advantage. i cannot monitor the debug box all day and i am not sure why we are forced to share with them, it should be an option. i would prefer not to make my shares buddy-only which to me is the next closest thing to not sharing at all, i like sharing, just not with people who refuse to reciprocate. as a user who currently shares over 32tb on my main account, and runs a few others for smaller files and special interests, this might be more of a problem for me than the average user sharing a few mp3.. but i know i am not alone in this sentiment. of all the problems with soulseek, this one is the most frustrating. any information or help is appreciated as always.

**Comment by mathiascode** [comment]
I could add a plugin option to open the private chat tabs again. The original intention according to the code was to silently send these messages, and this behavior was restored as a result of bug fixes.

It's very unlikely that I'll ever accept an auto-ban feature into Nicotine+ by default. Certain features like country blocking can already be considered controversial, and I don't want us to gain a reputation of being the black sheep among third party clients and risking to be kicked off the server.

This doesn't stop you from creating your own variant of the leech detector plugin, though. Nowadays, banning a user would just require a single line change in the plugin's code.
