### ISSUE TITLE
Option To Selectively Rescan Specific Folders

### ISSUE THREAD

**Issue by tacosuzy** [nicotine-plus/nicotine-plus#1514]
### Describe the solution you'd like
I wonder if it would be possible to add an option to chose a specific set of folders to not rescan with rescan at startup enabled. I have a large number of files in multiple folders on different HDD's and with rescan enabled it scours through all the files and can get time consuming.

My reasoning is I only have 1 folder that is actively updated that would need to be rescanned.

**Comment by slook** [comment]
Interesting suggestion @tacosuzy I have a similar shared folder configuration myself...

The mechanism you have suggested (you mean like as a column of checkboxes in the Preferences > Shares?) might be challenging for the devs to implement cleanly due to the complexity of the startup sequence.

![nicotine-plus Rescan Individual Folder](https://user-images.githubusercontent.com/88614182/131680165-838f7d8b-5349-41b4-a8ef-91a002c87a53.png)

May I suggest a simpler alternative in the meantime just a simple "Rescan Now" button alongside those 3 buttons would be helpful?

_Please note: If this feature was added, then the "Rescan Public Shares" menu item would need to be renamed to "Rescan All Public Shares" (insert the word "All")._

**Comment by tacosuzy** [comment]
That was precisely my meaning. Your idea of having a button beside a location to manually scan would work. Checked would be actively rescanned, and unchecked would halt the scans of those locations until the box is checked.

For the time being I have since removed the other folders and am back to a single folder to sync. Since I don't required this feature I will close this for now as I'm not sure if I should leave it open.

**Comment by slook** [comment]
@tacosuzy Please keep this issue open if you would like the devs to consider your suggested enhancement. Thank you.

**Comment by tacosuzy** [comment]
Reopened. My bad.

**Comment by mathiascode** [comment]
This isn't possible to implement short-term due to our current architecture.

**Comment by tacosuzy** [comment]
Alright, thanks for responding.

**Comment by slook** [comment]
I see that [your suggestion](https://github.com/nicotine-plus/nicotine-plus/issues/1514#issue-985062068) remains open for future consideration. In the meantime, there are ways to optimize your configuration...

Nicotine+ will only need to rescan a shared folder if one of the files in it has changed or you have added a new file into it... This works well for indexing many small sub-folders, but not so well for indexing big folders containing a very large number of files.

> I have a large number of files in multiple folders ... ... it scours through all the files and can get time consuming.

If your rescans are often taking a long time, this indicates that you have an infinitely growing folder? If this is the case, then I suggest if you split this up into multiple sub-folders (perhaps by each file's Creator, Type, Year, or other such category), this will make the rescan process much faster.

**Comment by tacosuzy** [comment]
I wasn't sure if I was supposed to leave the request open. Since it was stated that it is not yet possible, I will close this request.

**Comment by slook** [comment]
Thank you @tacosuzy I will note this in [Developer Discussion](https://github.com/nicotine-plus/nicotine-plus/discussions/1533#discussioncomment-1310053) for long-term consideration.

**Comment by komic** [comment]
Sorry for bumping this. I'm probably stupid, but if "Rescan shares on startup" is disabled, am I supposed to initiate a manual scan somehow?
