### ISSUE TITLE
Forcibly re-queue uploads that stop due to an error such as "Can't connect"

### ISSUE THREAD

**Issue by Tenome** [nicotine-plus/nicotine-plus#1563]
I noticed someone grabbing some music from me whose upload was stopped due to "can't connect." When I click on them and hit Retry, it works just fine, so presumably the connection timed out or something. Can there be an option to automatically retry any uploads (and downloads if it isn't already a feature) so neither me nor the downloader have to hit Retry?

Thanks for your work.

**Comment by mathiascode** [comment]
This is implemented for downloads, but not uploads yet.

**Comment by slook** [comment]
> When I click on them and hit Retry, it works just fine

It does for a single file, but selecting multiple files that all have the "Can't connect" status doesn't work (in 3.2.0.dev1), which makes it necessary to wait until all transfers have finished then go through each one individually. On slow connections this is very tedious (even when multiple upload slots are available).

Note that the Queue position of the stuck Uploads becomes duplicated in this scenario, which might be causing the inconsistent behaviour? Disconnecting+reconnecting doesn't resolve it, but restarting the application does, perhaps because all Queue position are then reset (perhaps "Can't connect" items need to be given a Null position in the Queue).

**Comment by mathiascode** [comment]
With the recent improvements to the queue system, this should be doable if we simply change the status text back to "Queued" and let the queue system pick up the transfer eventually. If the user doesn't want the file anymore, they'll reject it as usual.
