### ISSUE TITLE
Still Critical Error

### ISSUE THREAD

**Issue by h8uthemost** [nicotine-plus/nicotine-plus#1573]
I'm still getting a critical error when I either start, or do a fresh install of Nicotine. If I do a fresh install it'll allow me to do the Set Up process. Which is good because last critical it wouldn't even allow that. But once I hit the Close button the Crash Report pops right back up.

I'm sorry to be a bother...

By the way it's the latest version from the ppa repos. Even if I use the .deb I still get the same issue. 
Funny tidbit though, it's working just fine on Ubuntu. It's only on Debian that I get this problem. And unfortunately Debian is what I use more. Maybe it's time for a change though.

Anyways thanks for any and all help

Nicotine+ Version: 3.2.0.dev1
GTK Version: 3.22.11
Python Version: 3.5.3 (default, Apr  5 2021, 09:00:41) 
[GCC 6.3.0 20170516]

```
Type: <class 'KeyError'>
Value: 'nicotine'
Traceback:   File "/usr/lib/python3/dist-packages/pynicotine/pynicotine.py", line 396, in network_event
    self.events[i.__class__](i)
  File "/usr/lib/python3/dist-packages/pynicotine/pynicotine.py", line 1357, in user_left_room
    self.chatrooms.user_left_room(msg)
  File "/usr/lib/python3/dist-packages/pynicotine/chatrooms.py", line 167, in user_left_room
    self.ui_callback.user_left_room(msg)
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/chatrooms.py", line 330, in user_left_room
    self.joinedrooms[msg.room].user_left_room(msg.username)
```

**Comment by mathiascode** [comment]
Does this happen at the same point every time you start Nicotine+? If so, there is something peculiar going on.

**Comment by h8uthemost** [comment]
Yes, same point, every single time. Right after starting Nicotine+ the 
Critical Error window will display. Or 
right after hitting 'Close' on the 'Set Up' window if it's a new install, 
the Critical Error window will display.

I've tried just about everything that I can think of on my end. It might 
be a Debian issue since Nicotine+ runs fine in Ubuntu?

**Comment by slook** [comment]
> It might be a Debian issue

I am running N+ on several Debian 9 machines with the same exact versions of Python, GTK and GCC, yet I cannot replicate this issue.

```
Loading GTK 3.22.11
Loading Nicotine+ 3.2.0.dev1, using Python 3.5.3 (default, Apr  5 2021, 09:00:41) 
[GCC 6.3.0 20170516]
```

I have looked at the code raised the OP's Traceback, but I cannot find a reason why `__class__` would not be set correctly?

**Comment by mathiascode** [comment]
> I have looked at the code raised the OP's Traceback, but I cannot find a reason why `__class__` would not be set correctly?

The KeyError happens on (now) line 336 in gtkgui/chatrooms.py, even though there's an `in` check on the previous line. While the current check could in theory leave a small window for the `nicotine` room being removed from the joinedrooms dict in another thread, nothing like that should be happening in Nicotine+. It also doesn't make sense for the `user_left_room` method to  be called at the exact same time at the beginning of each Nicotine+ session.

**Comment by slook** [comment]
The only relevant commit that I can see that happened around the time of the original #1572 is https://github.com/nicotine-plus/nicotine-plus/commit/03dac14c221514abd4e67bc057bfdbd2275585a7 where the global hide/show country flags option was removed, but I can't see that has anything to do with it, especially given that this is now a new install so that should rule out a sort of config conflict. It seems more like some unicorn network conditions that just happen to trigger the error to occur upon the first (and last) demand for an interrupt in the OS network driver.

Perhaps the Traceback is just an arbitrary red herring (given network_event always seems to get the blunt end of any crash), but a pattern like the OP's is too consistent and severe to ignore.

I suggest is putting some sort of robust Except handler at the place of the standard log at... https://github.com/nicotine-plus/nicotine-plus/blob/b4e5c3d784b34c15416c753cf77588fa28f98965/pynicotine/pynicotine.py#L414 ...to see if more details about the KeyError can Try to be caught into a string, and then to force a disconnect if runtime execution is still possible. Perhaps this will be enough to enable debug logging so that more can be learned about the reason for this crash.

I suppose then we could arrange a config file that is crafted to have debug logging enabled, to be planted by the OP onto the affected machine?

Another option would be to always enable full debug logging-to-file on first run, and then disable it on the second run (at the point where the setup assistant isn't invoked). Whilst non-start crashes like this are very rare, currently we have no way of debugging them properly, because no debug log file is ever produced unless this has been explicitly enabled in the Preferences UI.

**Comment by mathiascode** [comment]
Likely fixed in https://github.com/nicotine-plus/nicotine-plus/commit/a5dd89f1e23decf24501676dfed34825bcb277bb. @h8uthemost could you check? The unstable PPA will be ready in a few hours.

**Comment by slook** [comment]
Something very similar was replicated when working on Wishlist tabs, that was related to certain scenarios where tabs that were automatically created are closed when they are the last remaining tab in that window, which was fixed in https://github.com/nicotine-plus/nicotine-plus/commit/82fa35affadb20bebc6663a9628f3413c98f0ab9

@h8uthemost please could you check the latest Unstable branch to verify if the latest commits fix the issue for you.

**Comment by mathiascode** [comment]
Closing for now, feel free to re-open with more updates if you still experience this.
