### ISSUE TITLE
filters button

### ISSUE THREAD

**Issue by 82d** [Nicotine-Plus/nicotine-plus#1601]
this will liberate the space, relieve and lead to a more hormonal look. if you need to hide/open the panel, you can easily do this through the context menu. a new successful add button to the list will move to this place, which in my opinion will look very good next to two buttons without inscriptions in the neighborhood. 
I have the filters panel always turned on so that I can quickly remove the settings that I have set in the settings and I have never needed hide and rediscover it.
![Снимок экрана_2021-10-07_23-21-11](https://user-images.githubusercontent.com/15121782/136427063-008ec80e-d940-4c0f-ab69-2a968da765f6.png)

_Nicotine+ 3.2.0.dev1
FreeBSD 12.2-RELEASE-p6_

**Comment by 82d** [comment]
or you can unify the Result Filters button so that it looks the same as Add Wish, remove the backlight, change the icon to + / -. then it will look much better.

**Comment by 82d** [comment]
I think the backlight is justified when there is a static icon on it. in the case when the icon changes, the backlight will be superfluous. I stick to the idea to lighten the interface, to unload visually at the same time to leave the functionality.

**Comment by slook** [comment]
Yes I love this free-form design philosophy similar to foobar2000, I personally use DeaDBeef on Linux for the same reason as you. 

Unfortunately this is very difficult to implement. It will be a very long time before anything like this will be possible in N+, the closest we have to this is options on which side the tabs are for each mode, but even this was a struggle.

**Comment by 82d** [comment]
![Снимок экрана_2021-10-07_23-21-11](https://user-images.githubusercontent.com/15121782/136468370-fc2f96a0-787d-43c5-8044-41a653aa0de3.png)

**Comment by slook** [comment]
> the program is designed for long-term use

Of course we want users to run the application as much as possible, but there are likely to be users who rarely open it once in a blue moon, so we don't want to put new/infrequent users off with a plethora of "pro" options.

**Comment by 82d** [comment]
> > the program is designed for long-term use
> 
> Of course we want users to run the application as much as possible, but there are likely to be users who rarely open it once in a blue moon, so we don't want to put new/infrequent users off with a plethora of "pro" options.

the option would have turned off all hints and pop-up explanations, which would have been activated by 1 or 2 checkboxes in the settings. and it is possible to make a choice on the first launch of the program. it's not like it won't affect simplicity or complexity. just turn off all the hints globally. I think many people liked it.

**Comment by 82d** [comment]
> Again this is unsuitable, clearly there is no sorting function accessed here. There's not much to choose from Gtk icons are rather limited, I can see why mat has chosen the find-replace icon.
> 
> We try to stay away from up and down arrows, because such icons are too easily confused with Upload and Download, in addition to the Expand / Collapse buttons.

I didn't specify that I use Xfce 4.16.0. what sets of themes are currently suitable for icon search besides gnome?

**Comment by slook** [comment]
I must admit I do like the idea of the `view-pin-symbolic` icon, this has been discussed before somewhere, but it was decided that it would indicate a function whereby the Filters apply to all other open search tabs when active, so it would therefore be unsuitable here with the way things operate at the moment.

Agreeably the rewind and previous-track icons do look a bit bulky, but I like the fact that the bar |< appears when active. Unfortunately, the reversed play `media-playback-start-rtl-symbolic` icon doesn't have this variant, so we would be loosing functionality there.

Sorry to be so critical of your suggestions, they are good and I see why you've suggested them, but there has to be a more compelling case if they are to be changed, because the ones you have suggested both have drawbacks of their own.

As you can understand the limited selection of icons offered at runtime by the native environments, if there are more cases like these in the future then I suppose we would have to consider generating a custom icon set that fits our needs better, but for now this is not a high priority issue so this is unlikely to happen any time soon, unless someone comes up with something concrete.

See: `Preferences > User Interface > Icons` (at the bottom of that settings page). Notice the 'Icon theme folder' button is "(None)" and doesn't lead anywhere useful, it seems to be half implemented for the purposes of main window tab notifications, I guess this is area which would benefit form more work, but right now it does what is needed so there is little motivation to expand on this.

**Comment by slook** [comment]
@mathiascode I think this issue can be closed in favor of #1400 since https://github.com/nicotine-plus/nicotine-plus/commit/487d42445bdd959716dee8df6295bdb70ef365f5 has made a nice improvement to the appearance of the Search Files toolbar, and no other Gtk icon is currently available that is better than the one you have already chosen.

@82d Please feel free to continue discussion about icons and suchlike either in this thread or toolbar layout issues [here](https://github.com/nicotine-plus/nicotine-plus/discussions/1535#discussioncomment-1444130) (after this issue is closed if you @ tag me I will see it), or if you have any further suggestions that you feel need attention from the devs then your feedback is always welcome.
