### ISSUE TITLE
Determine the size etc of a folder / selected files

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1628]
### Describe the solution you'd like
Currently, there is no way to see the properties of a folder when right-clicking a user's folder. I'd like to know the size of a folder, and similar information as is shown for "_File_ properties" on files.

### Additional context
If one selects multiple files and chooses "_File_ properties", we get a dialogue box "File Properties (x of y)", where we can step through each file and see its details. In some circumstances, this may be what you want, in others, you may actually want to know only the common details between the selected files: total file size, total length (if only files with a length value present), total number of files, etc. Some fields could show "(multiple)" if the value differs across files.

If a hypothetical "_Folder_ properties" option were to be introduced and be useable on a _folder_ shown on the Search Files tab, I think it should show the folder's details (or for multiple folders if selected) regardless of what the filters are set to. If one would want to know the size of only the files that can be seen (due to an active filter), one could select all the files > File properties, and then have a button on the pop-up which toggles between seeing the "(x of y)" view, and an aggregate view, i.e. per file vs all. This aggregate view would be what "_Folder_ properties" would display, but only for the selected files.

Thanks.

**Comment by slook** [comment]
In my local dev fork I am working on a Statusbar implementation in User Browse which provides this functionality for total number of files in a folder, and the size of a multi-selection of files, it works pretty well.

My future intention is to implement similar functionality into master. Unfortunately my code is not particularly graceful at the moment, and changes to the Statusbar are needed so that it can be implemented cleanly.

**Comment by mathiascode** [comment]
Due to complexity concerns related to having a separate field for folder size (only displaying the size of visible files of a folder in search results would be misleading), I've opted to only show the total size / duration of selected files. You can of course select a folder and get the total stats for it this way.
