### ISSUE TITLE
Conform to Windows window-arrangement hotkeys

### ISSUE THREAD

**Issue by sailormoob** [nicotine-plus/nicotine-plus#1704]
### Describe the solution you'd like

The Nicotine+ client window should respond accordingly to the following commands:

- Minimize the current window: Windows+Down Arrow
- Maximize the current window: Windows+Up Arrow
- Minimize all windows: Windows+M
- Restore all minimized windows: Windows+Shift+M
- Maximize on left: Windows+Left Arrow
- Maximize on right: Windows+Right Arrow
- Move a window precisely: Alt+Tab for context menu, then arrow keys to select menu item, then Enter key to select an item, then appropriate keys per item to carry out its function

### Additional context

Win10 Pro (21H1) recently updated
Nicotine+ 3.1.1
Currently the Nicotine+ client window is unresponsive to any of these commands.

**Comment by slook** [comment]
Nicotine+ doesn't use nor handle the global system keys you have listed @sailormoob , it is up to the Windows shell to manage those commands, because the client window doesn't pass any key-press events between itself and the shell.

This requires further testing to verify that the Nicotine+ application window is not blocking any key events it shouldn't capture. thank you for reporting the issue, unfortunately Windows testing is limited although this has improved lately.

Several improvements have been made to keyboard accelerator handling in the [latest Unstable builds of Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows) 3.2.0.dev1 that should hopefully remedy the problem, are you able to install and run a testing version to check if the incorrect behaviour has already been resolved?

**Comment by mathiascode** [comment]
I'm guessing this is an issue with GTK and client side decorations (headerbar). Do these shortcuts work if you disable the header bar (Menu -> View -> Use Header Bar)?

**Comment by sailormoob** [comment]
Ah yes @mathiascode is correct, the header bar needs to be enabled.
