### ISSUE TITLE
Download file(s)/folder(s) as paused

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1717]
### Describe the solution you'd like
Sometimes I find myself rushing over to the Downloads to try and pause whatever files/folders it is I have just chosen to start downloading, to do so before any files start/complete. It would be great if there was a way to add the chosen files/folders to download in a paused state to the Downloads tab.

Say a folder you'd prefer to download is from a user who is offline, you add that to download, but instead of having to redo the same searches later on for an alternate source, a current but different download from the search results could be added in a paused state in case the offline user never comes online, or say, turns out to have a huge queue. There are other ways to deal with this situation, like keeping a wishlist item added, but in my case that adds to the clutter of an already large wishlist. Sometimes the search results are for a specific track when you're interested in the whole folder, downloading multiple results as folders in a paused state would be a quick way to compare what's available, which users aren't online, etc, and clear all but the one source that is preferred.

Maybe adding a download in a paused state is something others think would be a useful feature too?

Thanks.

Nicotine+ 3.1.1

**Comment by mathiascode** [comment]
Would a global option to add all downloads in the paused state be enough (I know some torrent clients have this option)?

**Comment by redactedscribe** [comment]
It's a bit of an all-or-nothing solution. Ideally it could be done on a per-download basis, but that would require either another context menu entry or a modifier key, both of which I think aren't ideas you're fond of. If there was a UI checkbox (i.e. "Download as Paused") that toggled a global preference located in the preferences, that'd make it more useable to me, though such an checkbox would then also need to be present on the User Browse tab too I imagine. What you suggest is better than nothing and could just serve as a starting point before a more convenient implementation is added later on.

**Comment by slook** [comment]
A global option to Pause all new downloads would seem like it would be more often frustrating than useful, but it might be worth try. I have never found a use for such option in torrent clients usually I want downloads to start ASAP.

> a modifier key... of which I think aren't ideas you're fond of.

It's not that we're not fond of this idea, I think an Alt modifier would be reasonable for this, but currently our menu actions don't support modifier keys yet, and some hint would be needed to document such a function exists, but the menu items don't yet support pre-activiation events that would be needed to implement this properly (ie; without wiping out the previous Statusbar message).

Since the Transfers lists are now remembered forever it seems, I have a feeling that an option to automatically select the most recently added item(s) would be even more useful, as new items are usually all the way down to the bottom of the scrolled window and beyond. If scrolling and highlighting happened automatically, then the `T` shortcut key would then immediately Pause the transfer, and enable other functions such as Enter for Send to Player etc (but an option would be desirable to turn the cursor movement behaviour off, because it could be confusing for some use cases).

**Comment by mathiascode** [comment]
> another context menu entry

You're right, I'm not fond of this idea. I've already been cutting down on the number of items in our context menus when possible.

Modifier keys could potentially work in the future, but I'm concerned about proper hints for these so that they don't end up as secret features used by one person.

**Comment by mathiascode** [comment]
Then there's also SoulseekQt's folder download dialog, which lists all files available in a folder and shows more options. Would something like this work?

![](https://user-images.githubusercontent.com/8754153/142741788-0f7659d6-5086-4c64-87d4-b5fbc46e48b6.png)

(This is also feature request https://github.com/nicotine-plus/nicotine-plus/issues/1659)

**Comment by redactedscribe** [comment]
> an option to automatically select the most recently added item(s) [...] scrolling and highlighting happen[ing] automatically

I have quite a long downloads list at the moment and it isn't fun trying to locate where newly added download is in it, so this would be welcome @slook. I'd enable such a feature (and maybe it should be enabled by default), but power-users could prefer to keep it disabled and instead trigger it manually via button/shortcut.

> At the moment we are looking for urgent bugs in testing Nicotine+ 3.2.0.rc1 as this is due for release to Stable soon (have you tried it yet?

I haven't, no. I decided to stick to stable when 3.1.1 came out. I didn't know 3.2.0 would end up being such a big release, else I'd have probably participated more. I'll likely only have time to give feedback on it post its release unfortunately, but from what I've seen from keeping an eye on this repo, things look promising.

> Then there's also SoulseekQt's folder download dialog, which lists all files available in a folder and shows more options. Would something like this work?

Looking at what @mathiascode replied with, that certainly looks more usable than a global option (at least for my use cases) and would likely be all that is needed to add downloads paused on a per-download basis. I like it. Whether or not a global "download as paused" option is worth adding, that can be left for someone else to argue for.

**Comment by mathiascode** [comment]
Closing in favor of https://github.com/nicotine-plus/nicotine-plus/issues/1659
