### ISSUE TITLE
Filter for song length

### ISSUE THREAD

**Issue by brutalbombs** [nicotine-plus/nicotine-plus#1727]
I really miss a feature to filter on song length in both nic+ and slsk as of now. I usually encounter this problem when I'm looking for a special song, but this song is either included in mixes or collections. Usually one could just filter out the false positives by adding "-[collectionname]" to the search string, but at times the song is just renamed and looks like the original file I'm looking for.

This is especially tedious with wish-list searches, as they keep finding the same short 4m30s song when i'm looking for the 6m20s version.

What i would really like is to be able to set a SONG LENGTH filter with operators like >, <, = something akin to this:

1. sl>2m30s
2. sl<5m0s
3. sl=2m33s

This would greatly help when doing some pretty deep digs with the wishlist function.

**Comment by slook** [comment]
I agree @brutalbombs a Length filter is missing, and is very relevant for the file types concerned.

Since the Result Filters bar is rather crowded, this needs figuring out so that the additional Length filter can be added. I note that Speed is also missing (but is less important than Length). This makes me wonder if it could be worth toggling on/off the desired filter types to help with https://github.com/nicotine-plus/nicotine-plus/discussions/1535#discussioncomment-1444130

As to integration of Filters with the Wishlist, this is something that is planned for a future release, and as you pointed out, the old results quickly become annoying and this prevents the feature being used to it's full potential, see https://github.com/nicotine-plus/nicotine-plus/discussions/1604

Recent and ongoing improvements to the Result Filters allow scope for your suggested improvements in the future (after the next Stable release or two), see https://github.com/nicotine-plus/nicotine-plus/issues/1400

> something akin to this:
>    `>2m30s`

Hopefully the parsing of filters will allow for either the `h:mm:ss` or `Hh Mm Ss` syntax for song length.

**Comment by slook** [comment]
@brutalbombs The feature you requested has been added into Search Files (but is not yet integrated for Wishlist searches see open issue #1887 still in progress).

You can use the [latest unstable build](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md) Nicotine+ 3.3.0.dev1 to test it out. Any feedback would be most welcomed.

"Duration" filter query format can be `HH:MM:SS` or `MM:SS` or `S`

_Multiple conditions can be in any order, for example..._
`>7:00|<11:00|!7:30|!7:33|!6:46|=12:45|=260|=1:58:30`
_... shows:_
- all tracks between 7 and 11 minutes long, except for...
- hide tracks that are exactly 7:30 or 7:33 or 6:46 long
- and also show songs that are exactly 12:45 long, exactly 260 seconds, and exactly 1h58m30s long.

_For the Duration filter, = "exactly" means to within 1 second (decimals are not supported)._

Please also see the text in Preferences > Searches > Result Filter Help > Result Filter Usage if that makes sense.

Any feedback would be most welcomed.

**Comment by brutalbombs** [comment]
@slook Sorry for the late reply - this looks really great. I've been trying to run the filters for some time now and so far I'm happy with how you've developed them.

That being said, I've tried to "bake" the filter into a search string for wishlist searches, but so far i haven't made it.

I've disabled the setting "Remove special characters from search terms" under Preferences → Searches, and added e.g. ">4:00" to a string. I know this result should get hits from a separate search without the length filter, but it doesn't seem to work this way.

Is there any hopes of getting it into the main search string?

**Comment by slook** [comment]
No, it cannot work that way, we need to make the filtering modular in order to integrate it with wishlists (and possibly in future other parts of the application such as Browse Shares etc).

This is discussed in https://github.com/nicotine-plus/nicotine-plus/discussions/1604 and planned in https://github.com/nicotine-plus/nicotine-plus/issues/1887
