### ISSUE TITLE
I cannot see my profile info and picture like I am able to on other user's profiles

### ISSUE THREAD

**Issue by kiril-u** [nicotine-plus/nicotine-plus#1751]
Hi

When I search myself (on 'User Info'), for instance, my page shows likes, dislikes, but it doesn't show information and a photograph like on other pages. I did fill in information in my options and i have uploaded a photograph.
I'm not sure if that's a bug or an error on my behalf. I have tried searching my profile from a different machine and different user and the result was same.

I'm currently "privileged" (as in i donated to soulseek) if that means anything regarding this issue.

Good day! 

Edit: I cannot remove likes or dislikes. Port configuration is as such that people are able to search and download music from my library

**Comment by slook** [comment]
Thank you for reporting the issue regarding the user picture, it sounds familiar so I'm not sure if this might already be fixed in the [latest Unstable](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md) version of Nicotine 3.2.0.rc2 ... Please specify your Nicotine+ version @kiril-u ?

> I cannot remove likes or dislikes

This is not done from the User Info tab but rather in the Interests tab.

**Comment by kiril-u** [comment]
Thanks for your attentive response.

OS: GNU/Linux Debian sid (unstable)
Program version: 3.1.1-202108020445~ubuntu18.04.1 and nicotine 3.2.0-202112060017~ubuntu20.04.1.

Likes and dislikes work as intended when done correctly as you said.

>it sounds familiar so I'm not sure if this might already be fixed in the latest Unstable version of Nicotine 3.2.0.rc2

While testing, the profile pictures and user info of all online users were missing on nicotine 3.2.0-202112060017~ubuntu20.04.1.

I get the following message while checking any random online user (including myself): https://i.imgur.com/cpBuWUt.png.
Router configuration page and ss/netstat report that my machine address is listening on one of the ports assigned to NicotinePlus.

Asking for your patience for a follow-up in a day or two. I'll make sure my devices aren't misconfigured, check if it is related to ISP port blocking, and whether or not the issue reoccurs on two different architectures and distributions.

**Comment by slook** [comment]
![image](https://user-images.githubusercontent.com/88614182/144818805-2b58773a-526a-4e90-bf13-8e105d0797bb.png)

> Port configuration is as such that people are able to search and download music from my library

This can be the case if your port is either open or closed, since if the other user has an open port then this allows browsing.

You may verify if the server thinks your port is configured correctly at http://tools.slsknet.org/porttest.php?port=

**Comment by kiril-u** [comment]
I have reinstalled my OS and all seems to work now. I suspect that it was an error in my firewall configuration. This issue may be closed now. Thank you for your attention.
