### ISSUE TITLE
All file paths are reversed (e.g. /home/foo/Downloads -> /Downloads/foo/home/)

### ISSUE THREAD

**Issue by cookiengineer** [nicotine-plus/nicotine-plus#1759]
Nicotine+ version:  3.1.1-1
Operating System/Distribution: (ArchLinux, Community Package)

### Describe the bug

In the "Search Files" view, every path of the results is reversed.
In the "Downloads" view, every path of the list is reversed, too.

For example, if you select the Download path "/home/cookiengineer/Downloads" via the GTK popup as the transfer target, the list (and all transfer entries) will be set with their "Path" to "/Downloads/cookiengineer/home/" and therefore fail to download.

This is the case for the "Search Files" view entry, too - and I would assume is also the reason why all transfers fail since I updated nicotine+ to 3.1.1.

### Steps to reproduce the bug

Search for "awesome" or basically anything and every single entry has the Path set in reverse.

Download any of those entries, and use "Download Files To" from the context menu, select a folder, then take a look at the "Downloads" view, where all Paths are now reversed, too.

**Comment by cookiengineer** [comment]
Just built from HEAD, and it's the same behaviour. All file paths are in reverse.

Screenshot: https://i.imgur.com/WnS4Qnm.png

**Comment by slook** [comment]
Not a bug, is feature intended for narrow column viewports, since the text on the left side is always visible. Admittedly it looks confusing so it can be turned off as per preference...

Preferences > User Interface > "Show reverse file paths in search and transfer views (requires restart)"

> and therefore fail to download

This option is purely cosmetic, it does not affect downloading so your connection problem must be something else.

**Comment by cookiengineer** [comment]
Yes, indeed this was the fix for the UI glitch. Thanks for the hint!
