### ISSUE TITLE
Add an option to print full paths relatively to their share

### ISSUE THREAD

**Issue by q3cpma** [nicotine-plus/nicotine-plus#1775]
### Describe the solution you'd like
Title says it all, seems more useful than the strange reverse path thingie.

**Comment by slook** [comment]
Please clarify @q3cpma, are you suggesting that only the parent folder name be displayed, such as "Folder Name"?

**Comment by q3cpma** [comment]
On Mon, Dec 20, 2021 at 03:55:08PM -0800, slook wrote:
> Please clarify @q3cpma, are you suggesting that only the parent folder name be displayed, such as "Folder Name"?
>

No, if the full path is `/home/user/myshare/folder1/folder2` and
`/home/user/myshare` is the share it belongs to, I'd like to see
`folder1/folder2`, because the share path itself is quite useless to the share
owner.
Of course, this only makes sense in the Upload pane.

**Comment by slook** [comment]
> more useful than the strange reverse path thingie

Ugly string hacks are not needed in an app called Catfish (in Xfce) because it's TreeView implementation dynamically aligns the Location text to the right with an ellipses on the left if the viewport is too narrow... a neat solution. See screenshot:

![image](https://user-images.githubusercontent.com/88614182/147740895-b026f7ed-106f-4fa7-bef9-a46ae2f2cf9d.png)

**Comment by mathiascode** [comment]
> Ugly string hacks are not needed in an app called Catfish (in Xfce) because it's GtkTreeView implementation dynamically aligns the Location text to the right with an ellipses on the left if the viewport is too narrow... a neat solution. See screenshot:

I'm too used to the reverse paths to replace them at this point. I tried this solution, but I found it difficult to read after a while.
