### ISSUE TITLE
Allow uploading multiple files to a user at once until limits are reached

### ISSUE THREAD

**Issue by toofar** [nicotine-plus/nicotine-plus#1782]
### Describe the solution you'd like
Currently only one file is uploaded to a user at a time. Consider the following case:

1. I have four open slots configured
2. I have one user who has requested several files for upload
3. We only upload one file at a time so most of my open slots are unused

Maybe maxing out the configured slots with uploads to one user isn't a desirable behaviour because of the assumption that bandwidth between the two of us would already be fully consumed by one upload. But I don't know if that is true. So here I am proposing the other behaviour to see what other people's opinions are (and because I already wrote most of the code before thinking of that downside).

I suppose I was thinking of slots being filled by "files being uploaded" instead of "users being uploaded to".

### Additional context
If it turns out the current behaviour is on purpose I have a branch that changes it to allow uploading multiple files to a user: https://github.com/nicotine-plus/nicotine-plus/compare/master...toofar:feat/upload_candidates_tests_and_tweaks?expand=1

And the first and third commits on that branch may be of interest in any case. The first adds some tests for `get_upload_candidate()` (although they could be changed to be less biased toward my proposed behaviour) and the third has a micro-optimisation for the new round robin code.

**Comment by mathiascode** [comment]
See https://github.com/nicotine-plus/nicotine-plus/discussions/1772

As long as concurrent uploads to a user aren't officially supported in the protocol and official clients, I won't support them in Nicotine+.

**Comment by slook** [comment]
Clearly a lot of thought has been put into @toofar 's suggested enhancements to the upload queue system, and I get the general sense that the current mechanism seems to be inadequate, so improvements would be desirable here.

My main issue with it is that the options are non-sensical. For example, why is it that ["transfers"]["uploadbandwidth"] and ["transfers"]["uploadslots"] cannot be set at the same time? Is it because they conflict with each other or is it because one option simply overrides the other due to the way it's coded? For a start, I propose depreciating the ["transfers"]["useupslots"] option, and allowing a value of "0" to set 'unlimited' or "100000" rather than "1" (unless this isn't allowed on the server?).

Idk if @toofar 's code and test unit can hopefully be re-purposed to provide the improved functionality in compliance with the slsk protocol specifications?

**Comment by toofar** [comment]
> I'm testing concurrent transfers to a single user at the moment and am finding that Qt and Nicotine+ handle them just fine while NS does not

Ah, that's a pity. I didn't think about other clients making assumptions :slightly_smiling_face: 

> why is it that ["transfers"]["uploadbandwidth"] and ["transfers"]["uploadslots"] cannot be set at the same time?
> I propose depreciating the ["transfers"]["useupslots"] option

I could get behind that.

> improved functionality in compliance with the slsk protocol specifications

I'll change the test a bit to make more sense in light of the current behaviour being on purpose, and raise a PR. But I didn't change any functionality beyond that!

**Comment by slook** [comment]
Thanks for your contributions @toofar this is much appreciated.

Yeh, sometimes working within the confines of the slsk protocol might seem to be limiting (pun intended), but it has stood the test of time so these limitations often have sound reasoning in most cases, even though it might not seem obvious at first.

I don't know if removing `useupslots` is viable yet (it's probably okay). See my PR commit https://github.com/nicotine-plus/nicotine-plus/pull/1783/commits/dd0ce6bdbecd52103cd14ea604f5d165766cd09a which doesn't seem to stop anything from working, although I cannot verify this for sure because my knowledge and resources are... err, limited!

If you have any other suggestions as to how the queuing/limiting functions can be simplified, that could be very helpful at this point, because in the far future other features are intended such as scheduling and separate speed rates for Buddies (and other user defined groups that may be added in the future), etc... Perhaps your testing will shed some light on the matter.

**Comment by mathiascode** [comment]
Since the original proposal was addressed and https://github.com/nicotine-plus/nicotine-plus/pull/1784 was created, I'll close this.
