### ISSUE TITLE
Chat mentions with 1 character username

### ISSUE THREAD

**Issue by b1scoito** [nicotine-plus/nicotine-plus#1790]
Nicotine+ version:  
Operating System/Distribution: Windows 10 21H2

### Describe the bug
If the message contains my username, in this case the character `b` I get mentioned in chat.

### Expected behavior
Only get mentioned when someone actually sends `b` separately or `@b`

### Steps to reproduce the bug
Send a message with a word that contains `b` in some of the channels I'm in

### Additional context
![image](https://user-images.githubusercontent.com/17802984/147867118-e982c284-009c-48a2-8fc3-24c85741e714.png)

**Comment by slook** [comment]
The same issue applies to any length username, the mentioned search should match the exact phrase, but it doesn't, so any common word username suffers from this issue.

Perhaps the solution would be to check for the presence of a leading and trailing space around the matching phrase in the text.

**Comment by hboetes** [comment]
"word boundaries" is what's needed here.

**Comment by slook** [comment]
Thanks, that's the term I was looking for... Ironically, `\b` is the RegEx function for doing that. We don't have the `re` package imported in this module, it might be worthwhile since I can't think of a clean way to do it without regex, but I have a fear that it's presence might cause something unexpected to happen elsewhere.

**Comment by mathiascode** [comment]
Soulseek usernames can consist of any special character, so you also have to take this into account.

**Comment by hboetes** [comment]
"\b" nice new username, come to think of it.
