### ISSUE TITLE
Support upload requests for files that come in all in lower case

### ISSUE THREAD

**Issue by toofar** [nicotine-plus/nicotine-plus#1827]
### Describe the solution you'd like
In the debug logs I often (like on the order of 10 per day) see upload requests being rejected because the requested file isn't in the database. Most of them actually are shared but the requested path comes in all in lower case, whereas the real file has some upper case characters etc (there are a few of these cases that look like they are due to encoding differences too but not many)

For example:

```
[Transfer] QueueUpload request: User someuser, {'conn': <pynicotine.slskproto.PeerConnection object at 0x7f5a47c04b80>, 'file': 'music\\some\\file.flac', 'legacy_client': False}
[Transfer] Checking if file is shared: music\some\file.flac with real path /home/user/media/music/some/file.flac
[Transfer] File is not present in the database of shared files, not sharing: music\some\file.flac with real path /home/user/media/music/some/file.flac
```

But the file /home/user/media/music/Some/File.flac does exist.

I'm assuming these requests are coming in from a buggy client. I've sent like 10 users private messages asking what client they are using and the only response I've got back so far is "old win client"

So I was wondering if anything could be done to help connect these poor souls deprived of capital letters with the files they are looking for?

I had a quick look and the only thing I could think of is making the virtual -> real a full mapping instead of just a prefix thing. And having a normalized version in the virtual side. Although if that is what is returned in searches it would make those results all lower case too. Also it might raise the memory requirements a bit, storing everything twice. Although it is just text.

On the other hand there must already be a database/structure optimised for searching (for the search results) so perhaps using that instead of (or in addition to) the direct lookup would be more flexible and not too expensive (it's not like upload requests are more common than search requests). Eg, search for similar files somehow and see if any of the results, lower cased, have the same path as the requested file.

### Additional context
none?

**Comment by mathiascode** [comment]
Nicotine+ expects the exact path it sent to other clients when checking the dict here: https://github.com/nicotine-plus/nicotine-plus/blob/50681b8b5b13cd772f50a0c0043c74611ecbce5a/pynicotine/shares.py#L637

This is an old bug in Soulseek NS, and only exists in the "Download folder" feature in search results. Perhaps it's possible to come up with some workaround, but I'm concerned about doing any kind of looping or other operations on the shares list that severely impact performance, since the number of folders can be in the 100k range after all. Museek+ has some ugly workaround, perhaps that could be looked into.

In any case, this is low priority on my list. I've just about had it with this ancient client that hasn't been updated in 10 years and barely works today.

Additional reading: https://github.com/slskd/slskd/issues/261

**Comment by toofar** [comment]
> this is low priority on my list

Understandable, and thanks for the info. I only searched the issues on this repo, didn't think about the rest of the internet.

I'll close this issue so it doesn't look like an outstanding problem with nic+. And add that link to my copypasta.
Maybe one day I'll go through my logs to see how often this comes up and see if that makes me feel like working on a PR or a plugin to auto complain to them.
