### ISSUE TITLE
[WINDOWS] "String too long" crash on notification popup

### ISSUE THREAD

**Issue by 4fff618** [nicotine-plus/nicotine-plus#1829]
Nicotine+ Version: 3.2.0
GTK Version: 3.24.30
Python Version: 3.9.7 (default, Nov 21 2021, 22:02:56)  [GCC 11.2.0 64 bit (AMD64)]

### Describe the bug
When i double click a file to downlad, nicotine+ crashed with an error:

Type: <class 'ValueError'>
Value: string too long (316, maximum length 256)
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/frame.py", line 1949, in _on_critical_error_threading
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/threading.py", line 973, in _bootstrap_inner
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/threading.py", line 910, in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/notifications.py", line 192, in work
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/notifications.py", line 204, in _notify

### Other info
Maybe is related to the notification popup on windows, cut the length of the string before showing it?

**Comment by slook** [comment]
> cut the length of the string before showing it?

That's what is supposed to happen...

https://github.com/nicotine-plus/nicotine-plus/blob/fd9f1233972f00ab4220232676ddeac1a07c5d54/pynicotine/gtkgui/widgets/notifications.py#L204

Perhaps there were no boundaries in the string that caused the crash or something.

Suggest slicing by character instead of textwrap by word boundary @mathiascode :
`self.nid.sz_info = (message[:250] + "…") if len(message) > 255 else message`

But I cannot implement and test because I don't have a Windows box.

**Comment by mathiascode** [comment]
https://github.com/nicotine-plus/nicotine-plus/commit/480d2e1947cbdb4bc81cae501cec05311020cb3d changes the method of shortening messages.

@4fff618 Could you check if the latest testing build fixes the issue? https://nicotine-plus.org/doc/TESTING.html#windows

**Comment by 4fff618** [comment]
So far so good, i can't reproduce the error with the testing build.
