### ISSUE TITLE
Nicotine+ can't be launched from network drive on Windows

### ISSUE THREAD

**Issue by uniss2209** [nicotine-plus/nicotine-plus#1843]
Nicotine+ version:  3.2.0 portable
Operating System/Distribution: windows 11 22000.434

### Steps to reproduce the bug
run from network drive

### Additional context
Nicotine+ Version: 3.2.0
GTK Version: 3.24.30
Python Version: 3.9.7 (default, Nov 21 2021, 22:02:56)  [GCC 11.2.0 64 bit (AMD64)]

Type: <class 'FileNotFoundError'>
Value: [WinError 3] The system cannot find the path specified
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/frame.py", line 2074, in do_activate
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/frame.py", line 232, in __init__
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/pynicotine.py", line 291, in start
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/shares.py", line 490, in __init__
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/shares.py", line 499, in init_shares
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/shares.py", line 787, in rescan_shares
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/multiprocessing/process.py", line 121, in start
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/multiprocessing/context.py", line 327, in _Popen
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/multiprocessing/popen_spawn_win32.py", line 73, in __init__

**Comment by mathiascode** [comment]
"run from network drive" Could you expand on this? How is the network drive set up? Running Nicotine+ from a network drive has never been tested before, and it seems like Python's multiprocessing feature is choking up here.

**Comment by uniss2209** [comment]
The archive with portable version was unpacked at the address 
\\192.168.1.250\install\multimedia\p2p\Nicotine+
and exe was launched from there and then there was an error.
After your answer, I copied the folder with the program to disk C and it started without errors.

**Comment by slook** [comment]
While this is an interesting observation, this sort of behaviour is to be expected, since Windows doesn't allow the remote execution of binary programs for normal system users under the default GPO permissions.

Do you have a specific use case for running the portable exe over the network @uniss2209 ?

**Comment by hboetes** [comment]
Are there other programs that do work when started from a network drive?

**Comment by slook** [comment]
Really small utilities that don't have any dependencies generally work, such as if they are written in C.

I think as soon as a program has dependencies on external libraries then this is where problems tend to arise.

**Comment by uniss2209** [comment]
> Are there other programs that do work when started from a network drive?

The disk where I store the programs has write permissions. All programs that I use work without problems. Except this one, of course)))

**Comment by slook** [comment]
I suspect the problem may occur with the reference to the Python multiprocessing library in the 'D:/a/_temp' folder on your system. On Windows it is a common problem for temporary files to be created incorrectly with restricted "Execute" permissions (which are different from "Write" permissions).

To help us figure out if the problem lies within the Nicotine+ executable or if it is related to the Python GObject / Gtk runtime library, perhaps you can test another application that has similar dependencies, there are [some apps on a list](https://pygobject.readthedocs.io/en/latest/#who-is-using-pygobject).

One of them is [MyPaint](http://mypaint.org/about/) (I've never tried it), link:
https://github.com/mypaint/mypaint/releases/latest

There is a Windows version _standalone.7z_ from the above link, if that (or any another Python/Gtk program) can be run from a network drive on Windows 11 then that would prove it must be somehow possible for the Nicotine+ portable package to do this too.

**Comment by slook** [comment]
Possibly relevant for @mathiascode : https://github.com/marcelotduarte/cx_Freeze/issues/54

**Comment by mathiascode** [comment]
> To help us figure out if the problem lies within the Nicotine+ executable or if it is related to the Python GObject / Gtk runtime library, perhaps you can test another application that has similar dependencies, there are [some apps on a list](https://pygobject.readthedocs.io/en/latest/#who-is-using-pygobject).
> 
> One of them is [MyPaint](http://mypaint.org/about/) (I've never tried it), link: https://github.com/mypaint/mypaint/releases/latest
> 
> Or Gaphor, link: https://gaphor.org/download.html#windows
> 
> There is a Windows version _standalone.7z_ from the above link, if that (or any another Python/Gtk program) can be run from a network drive on Windows 11 then that would prove it must be somehow possible for the Nicotine+ portable package to do this too.

Those are probably going to work fine. Judging by the original post, starting the separate process for rescanning shares is the problematic part, otherwise Nicotine+ starts fine.

**Comment by slook** [comment]
The issue with the broken path might come from the argument that is parsed:
https://github.com/python/cpython/blob/8fb36494501aad5b0c1d34311c9743c60bb9926c/Lib/multiprocessing/popen_spawn_win32.py#L57
`        cmd = ' '.join('"%s"' % x for x in cmd)`

Perhaps `%s` should be translated to a network path URI instead of a mapped drive letter. Idk where this process is called from or whether it's possible to modify said argument?

**Comment by mathiascode** [comment]
Relevant code in Nicotine+ is here: https://github.com/nicotine-plus/nicotine-plus/blob/6c1dcd0e8e75ca213922a6304f8aafa59b4e1768/pynicotine/shares.py#L727-L745

**Comment by slook** [comment]
@uniss2209 What is the exact path string of displayed in Preferences > Shares > Folder

Does it make any difference as to if this setting is a shared folder on a network drive vs. on your local machine?

**Comment by uniss2209** [comment]
> exact path string

\\192.168.1.250\music


> any difference

Application crashes even if path is local

**Comment by mathiascode** [comment]
My guess is that the multiprocessing module has trouble finding the bundled Python executable for some reason, but I can't say for sure until I've set up a network drive in my Windows VM.

**Comment by mathiascode** [comment]
Something is wrong with the `sys.executable` path. If I call multiprocessing.set_executable with a random invalid path, I get the same traceback as the original issue.

**Comment by slook** [comment]
I suspect there might be some issue with the path separators or suchlike.

> Embedders will probably need to do some thing like
> 
> `set_executable(os.path.join(sys.exec_prefix, 'pythonw.exe'))`

The unrelated issue #1869 appears like it could be affected by a similar type of problem. This doesn't make any sense to me.

**Comment by mathiascode** [comment]
@uniss2209 Are you still experiencing this issue on Nicotine+ 3.2.7?

**Comment by slook** [comment]
https://docs.python.org/3.8/library/multiprocessing.html#multiprocessing.set_start_method
"Note that this should be called at most once, and it should be protected inside the if name == 'main' clause of the main module."

Should we run a sort "power on self test" of multiprocessing when launching nicotine and implement the frozen case check to do set_start_method() in there instead of doing it in the shares module?

**Comment by mathiascode** [comment]
Looks like the issue has been fixed.
