### ISSUE TITLE
An option to silently run command when a download is finished

### ISSUE THREAD

**Issue by ewauq** [nicotine-plus/nicotine-plus#1847]
Hello and thank you for your great work on Nicotine!

I like to generate the audio spectrogram of each lossless file I download to check the quality since there is a lot of bad transcodes on slsk. So I put this command in the "Downloads > Events" settings and it works almost perfectly:

![image](https://user-images.githubusercontent.com/1007507/150681609-cbcb23f7-5c5d-4497-815e-4caf2cfeed18.png)

Almost perfectly because it makes pops up a window that always takes the focus and it is very frustrating.
I know it is possible to make a wrapper script to do so but it sounds like a bit hacky.

It would be nice to have a checkbox "run silently" next to the textbox or something like that .

I am on Windows 10 / Nicotine 3.2.0.

Thank you.

**Comment by slook** [comment]
The command execution is platform dependent, so it is difficult to know a built-in solution that would be cross-platform. A nice idea tho perhaps worth some investigation.

If you were on a bash like terminal such as Linux then the stdout can be piped with syntax `ffmpeg >/dev/null` , but since you are on Windows this won't work on your platform directly.

Instead you could try the ffmpeg options `-hide_banner` `-nostats` `-loglevel warning` ... In theroey if nothing is written to stdout then a window won't appear, unless there is an error.

Also there are several Windows tools that apparently provide a means of running commands silently, so it might be possible to prepend some program before ffmpeg in your command string, see link:
https://www.raymond.cc/blog/hidden-start-runs-batch-files-silently-without-flickering-console/

**Comment by ewauq** [comment]
> Instead you could try the ffmpeg options `-hide_banner` `-nostats` `-loglevel warning`

Unfortunately, this doesn't work. It produces an empty cmd window, but the cmd works great.

However the NirCmd workaround sounds good to me. I remember I already used it a long time ago, I will give it a try while waiting for a better solution.

Thank you @slook.

**Comment by skizzo** [comment]
Hi,

first of all, thanks for this brutally awesome app. 

Since this is the only issue I found that mentions the "Run command after file/download download finishes"/"Run command after folder download finishes" settings: I'm wondering what I'm doing wrong, since the logs tell me that my commands were executed, but they never actually do what they're supposed to do. 

For example, my command for the "Run command after file download finishes" setting is:
`echo "New File downloaded: $" >> /Users/steff/downloadsNicotine.txt`
but nothing is ever written to the mentioned file.

Thanks for any hints!

**Comment by slook** [comment]
Perhaps the file `>` pipe is not supported by the transfer_actions() hander:

https://github.com/nicotine-plus/nicotine-plus/blob/39162e2eedbb79c1ea1a86ee66a034cd2756eab2/pynicotine/utils.py#L424-L447

Suggest try using `tee` instead (it that command is present in your os) because it uses a standard `|` pipe:

`echo "New File downloaded: $" | tee /Users/steff/downloadsNicotine.txt`

**Comment by skizzo** [comment]
Thanks a lot @slook , your example using tee indeed runs, but: It doesn't add a new line but **overwrite the whole file**. I'd like to have a list of all folders that were downloaded, not just a one-liner displaying the last downloaded folder.. Thanks for any further suggestions!

**Comment by mathiascode** [comment]
We should check if the `execute_command` function can be removed in favor of something simpler, ideally handled by the OS. This is probably the only piece of code that hasn't changed in 10+ years.

**Comment by mathiascode** [comment]
This is another feature I would like to remove from the Nicotine+ core and implement as a plugin instead. Ideally, the core shouldn't contain anything that relies on running external commands (text-to-speech, now playing).
