### ISSUE TITLE
Mass PM

### ISSUE THREAD

**Issue by woollarding** [nicotine-plus/nicotine-plus#1860]
### Describe the solution you'd like

it was just pointed out to me that QT has the ability to send a mass private message to all buddy list users... if nicotine does this i have not figured out how yet.. would also be helpful to be able to message all user in my upload queue

**Comment by mathiascode** [comment]
The protocol message is there, it just needs to be implemented in the GUI. https://github.com/nicotine-plus/nicotine-plus/blob/master/pynicotine/slskmessages.py#L1986-L2001

**Comment by slook** [comment]
I had also spotted this in the protocol documentation a few times and wondered a similar thing:
https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/SLSKPROTOCOL.md#server-code-149

It would be my guess that the function has not yet been implemented because of the risk of it being misused by spammers, however as it turns out over time this doesn't seem to be a large issue on the network.

> be helpful to be able to message all user in my upload queue

For this use case I can see the benefit of having this function, it could be a useful idea. The transfers module stores a list of active and queued `users` which could be accessible from a plugin perhaps. It wouldn't surprise me if someone in the community has developed such a thing, but I am not aware if this is so.

A possible built-in implementation would be in the multi-select 'Users' context menu, perhaps a menu-item with a label such as "Send Broadcast Message..." (alongside the username sub-menu items) could trigger a text entry dialog.

Naturally this would lead to the requirement for multi-select in the Buddies list, so there is some additional complexity there to handle the context menus and whatnot. It's probably not a good idea to make this function available in Search Files.
