### ISSUE TITLE
Sharing mounted cloud folders?

### ISSUE THREAD

**Issue by martimpassos** [nicotine-plus/nicotine-plus#1869]
Hi, sorry in advance as this is not strictly about Nicotine per se but Soulseek's forum is quite dead. 

I've been using `rclone mount` to use my remotely-stored (Google Drive) tracks in DJ software such as Traktor. Since I don't have a lot of storage and do not like the idea of using an external drive for storing/sharing my files (also being able to access them from anywhere, like my phone, is a plus), I'm curious whether there is some sort of setup that makes sharing folders from cloud storage possible.

I have tried adding my mount location as a shared folder, but it appears empty to other users. Not sure if this is a limitation of p2p architecture per se or if it could be a feature to be worked on. Of course I'd be happy to help in any way I can, not yet a pro pythonista but learning a bit more everyday.

**Comment by slook** [comment]
> Not sure if this is a limitation of p2p architecture per se or if it could be a feature to be worked on

Correctly reading the filesystem into the shares database does seem to be a pain in some cases so I suggest it could be worked on. There's no technical reason why any path that can be browsed from the local machine would be off limits for adding to shares, but this isn't straight forward because Nicotine+ is cross-platform.

The shares scanner was well known to be one of the more fragile modules, this has massively improved in the recent year or two but there is always room for improvement :)

> not yet a pro pythonista but learning a bit more everyday.

One way to approach this issue might be adding some `log` lines into the code to help you identify the contents of variables and arguments so that you can perhaps discover where things go wrong by viewing _Log > [Debug] Miscellaneous_ in the Log History pane or in the console if you [run nicotine from a local Git folder](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#git).

In the pynicotine codebase, debug log lines can be easily added by calling the `log` module for example:
`log.add_debug("Value of folder is " + folder)`

Or you can try to step through the code and watch things in an IDE if you're into that sort of thing.

A place to start looking could be somewhere in the Scanner() class...

https://github.com/nicotine-plus/nicotine-plus/blob/cc1e87dc0f5714a019282b362787c5883738b0f3/pynicotine/shares.py#L279-L286

https://github.com/nicotine-plus/nicotine-plus/blob/cc1e87dc0f5714a019282b362787c5883738b0f3/pynicotine/shares.py#L500-L540

I suspect there might be some issue with the `path` seperators or suchlike.

**Comment by martimpassos** [comment]
Hi @slook thanks for your inputs, I'll make sure to give it a go. Just a consideration: this happens in the original Soulseek client as well. Could this be related to the network architecture instead of a being a Nicotine 'problem'?

**Comment by slook** [comment]
Local file sockets are handled by the Python interpreter, so a bug or limitation may exist that Nicotine+ is unaware of. The pynicotine Shares Scanner is unrelated to the slsk protocol.

The fact that this happens in the official Soulseek client is a coincidence, I could well be mistaken, but I don't see any particular reason why any path that can be browsed from the local machine would be off limits for adding to shares.

**Comment by martimpassos** [comment]
Soooo funny story. I actually wasn't using Nicotine+ until now (I had it downloaded but never really fiddled with). Turns out it works out of the box with the mounted drive, I just finished scanning my library and browsing my own shares shows pretty much everything (besides a few `invalid continuation byte` errors and the likes). 

Sorry for not testing this before, I posted here for the lack of a better 'official' Soulseek discussion channel (I tried the Google Groups discussion but not much help there too), and thanks for an amazing client! The very `browse public shares` functionality is something I've been wanting for a long time, precisely to be able to check this kind of thing without having to ask other users.

Now onto change internet provider in order to successfully open my ports...

**Comment by martimpassos** [comment]
> _"If you mount an rclone remote using the default, fixed drive mode and experience unexpected program errors, freezes or other issues, consider mounting as a network drive instead."_

I'm not on Windows so I suppose this doesn't apply

> _"Without the use of --vfs-cache-mode this can only write files sequentially, it can only seek when reading. This means that many applications won't work with their files on an rclone mount without --vfs-cache-mode writes or --vfs-cache-mode full. See the VFS File Caching section for more info."

I always enable `--vfs-cache-mode full` so I can edit my tags in Traktor and get the updates back on the cloud

**Comment by martimpassos** [comment]
Just asked for people on the chatroom to try downloading my stuff and seems to work. Closing this, thanks and sorry for the unnecessary trouble!

**Comment by slook** [comment]
Sweet. It would be interesting to know if it would work with `--vfs-cache-mode off` or not.

It's no problem you're welcome, we both learned some useful things today :)

**Comment by mathiascode** [comment]
> besides a few `invalid continuation byte` errors and the likes

If it's not too much trouble, could you send a log with these errors and some of these files to my email address (listed on my GitHub profile)?
