### ISSUE TITLE
Upload Slots Not Opening

### ISSUE THREAD

**Issue by woollarding** [nicotine-plus/nicotine-plus#1933]
Nicotine+ version:  
3.3.0.dev1
Operating System/Distribution: 
Window 11

### Describe the bug
nicotine will not open another slot unless i right click and retry the transfer manually

### Expected behavior
to make changes to the upload queue settings and more transfers start

### Steps to reproduce the bug
share files and have more than one user in queue, i believe i have tried all permutations of the upload queue settings... but as always if there is anything i can do to help test please do no hesitate to ask. thanks

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment]
Sorry I am not fully understanding the problem you referring to... is this about the behaviour of the queued uploads directly after having altered the upload queue settings in Preferences?

**Comment by woollarding** [comment]
yes, no matter what i set the upload queue settings to, i can only have 1
slot, if i want more than one to download at once, i have to right click
the transfer and start it by selecting retry. If, for example, i set it
from 1 to 3 slots, no new slots will open, same when i set the speed to
higher than i can upload which should open a slot for all users in the
queue, still just the 1 slot open.

**Comment by woollarding** [comment]
of course right after i send this email, all the slots start to open heh
maybe i was just being impatient but i swear it wasn't working for hours..
ill keep an eye on it

**Comment by slook** [comment]
It is to be expected that when the settings are just changed, then this won't take effect for existing transfers that were already queued before. I can imagine how this limitation might seem frustrating whilst testing different permutations of the settings, but this should not affect normal operation.

**Comment by mathiascode** [comment]
Could you send debug logs if this happens again (same logging categories as previously)?

**Comment by Climbatiz** [comment]
not sure why nobody has complained about this bug since March, i installed Nicotine+ v3.2.5 today and whenever most people try to download from me the download automaticly cancels and i need to click "retry" for the download to start, i'm running Nicotine+ latest on 2 machines and they can download from each other and i've seen at least two people running latest SoulseekQT who were able to download from me without my input aswell as a user using SoulseekNS (latest) who is on my Buddy list was able to download,  but at least 1 person failed who was using Soulseek 2017 version

i'm not sure if this is necessarily because of differences in client, but i'm suprised no1 else seems to be having this problem

note: upload slots being set to 50 is just for testing
![Untitled](https://user-images.githubusercontent.com/39280509/192307867-38002b15-c9f0-40a9-983d-511232b8a907.png)

**Comment by mathiascode** [comment]
If the upload status is `Cancelled`, it's a bug that will be fixed in 3.2.6.

**Comment by mathiascode** [comment]
> i have also seen uploads that hang on start of File Transfering, but this rarely happens

06ab75b181baefc71e75521cbb9f9e2dfdaba3fb should've fixed this.
