### ISSUE TITLE
I need file sizes to be displayed in bytes, not interested in abbreviated MiB sizing.

### ISSUE THREAD

**Issue by rolex905** [nicotine-plus/nicotine-plus#1948]
Hello there, I just discovered the app and was looking forward to using it, but I can instantly see a major problem that is totally unacceptable for me:  results and file lists are being displayed in MiB format instead of exact BYTES the way Soulseek client does.

I have not been able to use Nicotine because of this.  When I search for files I am looking for very specific file sizes that match up with torrents I would like to also seed, so abbreviated format does not, and will never work for me.

Let me know if there's any way to toggle this back to the original functionality of displaying full file sizes.  Furthermore, clicking on file details within the results ALSO is displaying an abbreviated file size in MiB.  Why?

**Comment by slook** [comment]
> I just discovered the app

Welcome :)

> file sizes that match up

This is a good point, I also like to refer the last 3 or so digits of a file to verify if it is identical to the original version of the file, or if it has been modified in some way. With audio files, slight difference in size usually indicates it has been re-tagged or the cover art is missing etc. Since the epoch, this has been a standard and expected feature of any program that manages files.

> I have not been able to use Nicotine because of this.

You are probably not the only one.

> clicking on file details [File Properties] within the results ALSO is displaying an abbreviated file size in MiB

I have this on my development fork so I shall request it be added into master.

> Why?

afiak, nobody else has ever raised this issue or desired to implement Bytes display in the GUI before. Thanks for raising it.

> Let me know if there's any way to toggle this back to the original functionality of displaying full file sizes

If you [clone and run from a local Git folder](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#git), the File Search size column display is converted into KiB/MiB/GiB here:
https://github.com/nicotine-plus/nicotine-plus/blob/4a3c58e46bd96b32e15fea314e8b4087d464040d/pynicotine/gtkgui/search.py#L568

If you want thousands separators, change this line to:
`            h_size = humanize(size)`

Or if you just want a raw integer, just set h_size to size (which is stored for sorting purposes):
`            h_size = size`

Then the results look like this:
![image](https://user-images.githubusercontent.com/88614182/157340770-883f22c4-d7e7-4a10-bd22-fabf8801becd.png)

`            h_size = humanize(size) + " B"` to append a B on the end.

For Browse Shares it's here:
https://github.com/nicotine-plus/nicotine-plus/blob/4a3c58e46bd96b32e15fea314e8b4087d464040d/pynicotine/gtkgui/userbrowse.py#L530

Similar as above, change `human_size(size)` to `humanize(size)` or `size` according to your preference. Idk why there is no h_size in this module, that's a curious hack that needs sorting out.

To implement this as a user configurable preference is much more involved, work could be done in the `human_size()` function which is in utils.py to implement options from config.py set by one of the Preferences pages in gtkgui/settings, whilst considering that the code processed here needs to be iterated many thousands of times per second for each and every TreeView row.

Adding new settings into Nicotine+ is cumbersome, since the program is over 20 years old. Currently we are working on simplifying things before adding the many new features and options that users want/need. The list never ends!

**Comment by mathiascode** [comment]
> Adding new settings into Nicotine+ is cumbersome, since the program is over 20 years old. Currently we are working on simplifying things before adding the many new features and options that users want/need. The list never ends!

Adding settings isn't too difficult, but I'm more cautious about which settings are introduced nowadays. I'd rather not add more settings that are used by a single user, and clutter the preferences dialog for the rest.

Including the exact bytes in the file properties dialog is a good start, this matches the behavior of file managers as well.

**Comment by slook** [comment]
@rolex905 I've just discovered that pressing `Ctrl+C` when the filesize cell is highlighted copies the Bytes into the clipboard.

Then, pasting the clipboard into the Size filter entry with an `=` in front of it shows only files of that exact Bytes.

![image](https://user-images.githubusercontent.com/88614182/157641304-a228f6ba-ce3f-4c10-8c89-8d7c67d5cca5.png)

**Comment by bambury** [comment]
Thanks for adding the size in bytes in the properties. I am one of those who edit the sources to have search results and browse shares in bytes, so I would welcome an actual setting for this, but I understand the hurdles.

**Comment by mathiascode** [comment]
Would it be enough to only show file sizes in bytes in search results and browse shares? I don't want to do this in the download/upload lists due to issues with column sizing.

**Comment by bambury** [comment]
Definitely enough, as far as I'm concerned. Thank you!
