### ISSUE TITLE
ModuleNotFoundError: No module named 'pynicotine'

### ISSUE THREAD

**Issue by julled** [nicotine-plus/nicotine-plus#1953]
Nicotine+ version:  3.2.1
Operating System/Distribution: 
Manjaro 
```
➜  ~ uname -a
Linux xxx-t14 5.14.21-2-MANJARO #1 SMP PREEMPT Sun Nov 21 22:43:47 UTC 2021 x86_64 GNU/Linux

```

### Describe the bug

if i iinstall the community version of nicotine via yay there is pynicotine missing
```
➜  ~ yay nicotine
2 aur/nicotine-plus-git 3.2.1rc2.r6879.a5e1e62d-2 (+55 0.01) 
    A graphical client for the SoulSeek peer-to-peer system
1 community/nicotine+ 3.2.1-1 (1.4 MiB 6.8 MiB)
    Soulseek music-sharing client, written in python
==> Packages to install (eg: 1 2 3, 1-3 or ^4)

➜  ~ nicotine 
Traceback (most recent call last):
  File "/usr/bin/nicotine", line 21, in <module>
    from pynicotine import run
ModuleNotFoundError: No module named 'pynicotine'


```

### Expected behavior

nicotine starts

### Steps to reproduce the bug

see above

**Comment by slook** [comment]
> the community version of nicotine via yay

This is not an officially supported installation method for [installing Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DOWNLOADS.md#gnulinux-bsd-solaris)

> 3.2.1rc2

The version you obtained is an unsupported development version of Nicotine+ 3.2.1 Release Candidate 2, which is older than the [current stable version](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DOWNLOADS.md#gnulinux-bsd-solaris) of Nicotine+ 3.2.1

It seems like something is very seriously wrong with `yay` installation package, the error that should be displayed if the `pynicotine` module is missing, is:

> "Cannot find application modules.
> Perhaps they're installed in a directory which is not
> in an interpreter's module search path.
> (there could be a version mismatch between
> what version of Python was used to build the application
> binary package and what you try to run the application with)."

Since you did not see this error message, this indicates that the `pynicotine/` folder itself is missing from `/usr/bin/nicotine` due to some fundamental problem with the downstream package installer.

It could be that the Python interpreter on your system is trying to start Nicotine+ from your /home/~ folder. Perhaps try swtiching into the program folder first:

```
cd /usr/bin/nicotine
nicotine
```

Do you know who the yay package maintainer is?

**Comment by mathiascode** [comment]
> > the community version of nicotine via yay
> 
> This is not an officially supported installation method for [installing Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DOWNLOADS.md#gnulinux-bsd-solaris)

Assuming community version means the official Arch package from the community repos, it's supported.

> > 3.2.1rc2
> 
> The version you obtained is an unsupported development version of Nicotine+ 3.2.1 Release Candidate 2

The AUR package uses a slightly outdated tag, but fetches the latest commit from master when you install the package.

> If you have 3.2.1 then it seems like something is very seriously wrong with yay installation package, the error that should be displayed if the pynicotine module is missing, is:
> 
> ```
> "Cannot find application modules.
> Perhaps they're installed in a directory which is not
> in an interpreter's module search path.
> (there could be a version mismatch between
> what version of Python was used to build the application
> binary package and what you try to run the application with)."
> ```

We can't show the error if the code for it is inside the pynicotine module. It should be moved to the nicotine script.

> Since you did not see this error message, this indicates that the pynicotine/ folder itself is missing from `/usr/bin/nicotine` due to some fundamental problem with the downstream package installer.
> 
> It could be that the Python interpreter on your system is trying to start Nicotine+ from your /home/~ folder. Perhaps try swtiching into the program folder first:
> 
> ```
> cd /usr/bin/nicotine
> nicotine
> ```
> 
> An application should have been created so you would normally just start it from the GUI.

@julled What's the Python version on your system? The Arch package installs pynicotine at `/usr/lib/python3.10/site-packages/pynicotine/`.

**Comment by julled** [comment]
> @julled What's the Python version on your system? The Arch package installs pynicotine at /usr/lib/python3.10/site-packages/pynicotine/.

i have 3.9.1

> Assuming community version means the official Arch package from the community repos, it's supported.

Yes AFAIK yay only links to the official community version. But i am not a arch expert maybe i am wrong.
I actually didnt know that nictone installs stuff to /usr/bin/* . Should i have used yay with sudo?

**Comment by mathiascode** [comment]
> i have 3.9.1

This is the issue. The latest Python version on Manjaro is 3.10.2, and the Nicotine+ package expects 3.10.x (it installs at /usr/lib/python3.10/site-packages/, Python 3.9 would be /usr/lib/python3.9/site-packages/).

Upgrade your system packages (and keep the up to date in general) and the issue should be fixed.

**Comment by slook** [comment]
No problem at all @julled you are not being stuipid... the stupidness is with the Arch community package I don't understand what causes it to require a specific Python version, since Nicotine+ itself has a minimum requirement of Python 3.5 or above.

As to if you need `sudo` to install with `yay` that depends on your distro which we're not familiar with sorry, good luck!

Let us know if you get any further issues :)

**Comment by mathiascode** [comment]
> No problem at all @julled you are not being stuipid... the stupidness is with the Arch community package I don't understand what causes it to require a specific Python version, since Nicotine+ itself has a minimum requirement of Python 3.5 or above.

It's just the way Python works by default, modules are built for a specific minor version of Python. I believe only Debian has a patch to make use of a generic `/usr/lib/python3/dist-packages/` folder that works with any Python version.

**Comment by francisuk1989** [comment]
> > the community version of nicotine via yay
> @francisuk1989 do you know what's going on here, can you test this?

Everything works fine here, Manjaro KDE with GTK 4 and  python 3.10.2

I didn't install nicotine from pacman, just pacman -s gtk4 and then git clone and then NICOTINE_GTK_VERSION=4 ./nicotine

[kittycat@4bays nicotine-plus]$ NICOTINE_GTK_VERSION=4 ./nicotine
[2022-03-15 12:14:05] Loading GTK 4.6.1
[2022-03-15 12:14:05] Loading Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
[2022-03-15 12:14:05] Loading Nicotine+ 3.3.0.dev1
