### ISSUE TITLE
Nicotine+ 3.2.2 does not work on Windows

### ISSUE THREAD

**Issue by sbstn87** [nicotine-plus/nicotine-plus#1963]
Hi,

the latest build does not work on Windows 10. After trying to run it, nothing happens. The same happens with 3.2.1. Going back to 3.2.0 solves the issue. Uninstalling Nicotine first and installing either 3.2.1 or 3.2.2 does not help.

**Comment by mathiascode** [comment]
Two things to try:

1. Does the portable Windows version work?
2. Can you temporarily rename the `%AppData%/Roaming/nicotine` folder, and see if Nicotine+ starts?

**Comment by sbstn87** [comment]
1. The portable version does work and preserves my user settings.
2. After renaming the folder Nicotine+ starts as if it was a fresh install - asks to input username and password.

**Comment by mathiascode** [comment]
Can you back up your `%AppData%/Roaming/nicotine` folder, and temporarily remove files inside it (downloads.json and downloads.json.old at once, uploads.json and uploads.json at once, config and config.old at once), one by one, to see which one causes Nicotine+ to stop working?

**Comment by mathiascode** [comment]
Here's a build that should show output in the console, hopefully it will reveal something useful: https://github.com/mathiascode/nicotine-plus/actions/runs/2012428690

You need to start `Nicotine.exe` in an existing console window.

**Comment by sbstn87** [comment]
I tried removing the files you mentioned above, one by one, but Nicotine+ did start successfully each time. 

I cannot see the installer I can download in the link you have provided.

**Comment by hboetes** [comment]
> I cannot see the installer I can download in the link you have provided.

Try scrolling down a bit.

**Comment by sbstn87** [comment]
Here's the output I get:
---
PS C:\Program Files\Nicotine+> .\nicotine+.exe
Windows fatal exception: code 0xc0000139

Thread 0x00000f30 (most recent call first):
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1173 in create_module
  File "<frozen importlib._bootstrap>", line 565 in module_from_spec
  File "<frozen importlib._bootstrap>", line 666 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1058 in _handle_fromlist
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/site-packages/gi/__init__.py", line 40 in <module>
  File "<frozen zipimport>", line 259 in load_module
  File "<frozen importlib._bootstrap>", line 627 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/__init__.py", line 31 in check_gui_dependencies
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/__init__.py", line 73 in run_gui
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/__init__.py", line 237 in run
  File "D:/a/nicotine-plus/nicotine-plus/nicotine", line 34 in load_module
  File "D:/a/nicotine-plus/nicotine-plus/nicotine", line 38 in <module>
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/site-packages/cx_Freeze/initscripts/Console.py", line 15 in run
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 113 in run
[2022-03-21 07:06:48] Cannot find pygobject >= 3.18.0, please install it.

**Comment by slook** [comment]
There are 39 different causes for this error listed on the operating system vendors' website, all are equally vague...

https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x139--kernel-security-check-failure

> _"The KERNEL_SECURITY_CHECK_FAILURE bug check has a value of 0x00000139. This bug check indicates that the kernel has detected the corruption of a critical data structure."_



` File "D:/a/nicotine-plus/nicotine-plus/nicotine", line 34 in load_module`
` File "", line 259 in load_module`

Perhaps `load_module` is not a good name for the new wrapped function in the nicotine script, since it conflicts with the name of a function in the Python core, there could be some violation of an inadequately declared pointer or somesuch.

**Comment by mathiascode** [comment]
> Perhaps `load_module` is not a good name for the new wrapped function in the nicotine script, since it conflicts with the name of a function in the Python core, there could be some violation of an inadequately declared pointer or somesuch.

The name could possibly be improved, but it doesn't seem related to this issue. `load_module` did not exist in 3.2.1.

**Comment by slook** [comment]
What is baffling, is why the portable version works whereas the installer does not.

@vctls Have you tried the [portable version](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DOWNLOADS.md#official-release) on your system?

**Comment by vctls** [comment]
@slook yep, and indeed it works. Also, all my queues and settings are there, so I'm assuming it's using my home folder regardless of where I put the exe.

**Comment by slook** [comment]
@vctls cool, glad you are up and running. Yes the "portable" version uses the home folder path for config, just it doesn't require installation (this might change in a future version, because most would expect it to be entirely self-contained). You can also run the [latest unstable builds](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows) in this way for testing the latest bug fixes.

See the build mentioned above https://github.com/nicotine-plus/nicotine-plus/issues/1963#issuecomment-1073294059 if you are willing to help us with testing to verify with certainty if you are experiencing the exact same bug as the OP (and possibly many other Windows users).

**Comment by mathiascode** [comment]
@vctls I assume you uninstalled Nicotine+ 3.1.1 before installing 3.2.0? If not, there could possibly be some leftover files from 3.1.1 in the installation folder.

**Comment by vctls** [comment]
I'm not sure I did that. And I don't think I ever saw two entries in the program list.
I can try it anyway.
Why would it leave stuff when upgrading and not when downgrading, though?

**Comment by slook** [comment]
What is it that is stopping us from allowing a clean migration?

If we could identify the left-over files then perhaps the new installer could do a proper clean-up.

**Comment by vctls** [comment]
Is there any reason not to simply uninstall automatically the previous version if it's detected during the install process ?

**Comment by slook** [comment]
The complexity arises because the installer format was changed from pyInstaller to CX-freeze (which was done in order to dodge false-positive anti-virus reports), so the new installer does not know the previous GUID of the old installation.

Discovering the application key identifier by interrogating the Windows registry is not trivial, and furthermore us dev's here have very little experience in dealing with the inner workings of proprietary closed-source operating systems.

**Comment by vctls** [comment]
Makes sense.
Do you want me to try a diff of the files before and after installing 3.2.0 on top of 3.1.1?

**Comment by slook** [comment]
That could be very helpful yes please. With that information perhaps we could somehow avoid the runtime crash.

**Comment by mathiascode** [comment]
> Discovering the application key identifier by interrogating the Windows registry is not trivial, and furthermore us dev's here have very little experience in dealing with the inner workings of recent proprietary closed-source operating systems.

The previous installer was based on NSIS, and the new one is provided by cx_Freeze in the native MSI installer format. There was no way of linking these together, so the best I could do was to add a notice to our download page (you could change the default installation folder, but then you'd end up with two identical Nicotine+ entries in the menu).

**Comment by vctls** [comment]
Haven't done the diff yet but I can confirm that the bug occurs when doing the following:
1. Install 3.1.1 > OK
2. Install 3.2.0 on top without uninstalling > still OK
3. Install 3.2.1 _or_ 3.2.2 on top of 1 and 2, or just 1, without uninstalling > NOK, instant crash

I just now noticed the disclaimer about the installer on the release page. I feel even more silly.
<sub>(by the way, really appreciate the fact that the uninstaller doesn't crash because the folder is missing, unlike some other programs…)</sub>

**Comment by vctls** [comment]
Got it: the culprit is `libintl-8.dll`.
I can just leave everything else from the previous install but this one file. If I delete that one dll that sits next to the exe, the program launches normally.
Haven't checked for other possible issues after that, though.

**Comment by slook** [comment]
Something to do with the way path handling is changed in here perhaps @mathiascode ? https://github.com/nicotine-plus/nicotine-plus/commit/441e2aee372fc1ce2db4576c38aacfe81e30da96

**Comment by mathiascode** [comment]
I fixed the issue related to `libintl-8.dll`, but there are other conflicting dlls that will start to break once they evolve. The only real fix is to uninstall Nicotine+ 3.1.1 before upgrading to 3.2.0 or later.
