### ISSUE TITLE
Nicotine+ listening on port before manually connecting

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#2025]
Nicotine+ version: 3.2.2
Operating System/Distribution: Windows 11

### Describe the bug
Not sure if this is needed or intentional, or maybe an oversight, but when opening Nicotine with the Preference "Auto-connect to server on startup" disabled, the program launches already listening on the specified port. Maybe there's a good reason for this? I would have assumed it should only start listening once the user has pressed Connect.

**Comment by slook** [comment]
This is expected behaviour because Nicotine+ binds the local network interface once upon initializing, which is when the "Listening on port: " log message is generated. The `bind_listen_port()` operation is carried out regardless of whether we are connected or not.

However, perhaps it would be desirable to do the `bind_listen_port()` operation upon each `server_connect()` operation, then this would also have the advantage that an application restart would not be required each time the user needs to re-configures the port and binding settings. This could make trouble-shooting connection problems easier, however un-binding the local interface upon each disconnection could upset the user's network environment.
