### ISSUE TITLE
Add a Country flag column to the Uploads and Downloads view

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#2061]
### Describe the solution you'd like
I sometimes find myself curious of where a connection is coming from or going to, so an optional Country column in the Downloads and Uploads view that displays a flag icon, as is found in the Search Files view, would be a nice-to-have.

As a side note, displaying a flag along side a user's country value in the User Info view could be a nice visual touch as well.

**Comment by mathiascode** [comment]
Country flag in user info has been added.

For the transfer views, we need to get the country from the user's IP address when connecting to them, and store it in the downloads.json and uploads.json files for later sessions. This will not happen until the views have been ported to the new TreeView class.

**Comment by mathiascode** [comment]
On second thought, I don't want to add this column. I don't think it's worth adding this kind of information to the transfer list files, and if we don't do that, most of the flags will be empty after restarting. I don't see many requests for this feature from other users either.

However, I could add the country information to the file properties dialog, when available, since there's already a spot for it.
