### ISSUE TITLE
Choosing some files rather than the entire folder should still create the folder to hold them

### ISSUE THREAD

**Issue by DecayToDeath** [nicotine-plus/nicotine-plus#2091]
If I go to get an album on Soulseek but don't want the log file, artwork, or anything else sitting in that same folder, I'll generally just highlight all the tracks --> right click --> download selected. Normally, this outputs to a new folder within the designated download filepath that's titled according to the filepath provided by the user who's sharing them (much the same as if you selected "download entire folder", just without the unwanted files). Nicotine outputs these selected files loosely into my "completed" folder, which quickly becomes messy when requesting a great number of files. Not sure if this is a bug or the intended effect, but I've not been able to find a way to adjust it in the settings.

**Comment by mathiascode** [comment]
This is intentional, or has been the behavior in Nicotine+ for about 20 years at least (I believe it worked the same in SoulseekNS: https://www.slsknet.org/news/node/590). If you enable username subfolder downloads, it should save to the root of the username subfolder.

I'll eventually implement #1659, which will allow you to select the files you want before downloading a folder, including ones that might not be visible in the search results.

**Comment by DecayToDeath** [comment]
A username subfolder is one thing, I suppose I've always preferred the way it worked on my slsk client sorting them into the appropriate album folders. 1659 should solve my problem in a roundabout way, I think otherwise my only issue is with result display sorting.

**Comment by slook** [comment]
Closing in favour of #1659 

> otherwise my only issue is with result display sorting

This is unrelated to the issue being discussed here. If you have any other suggestion that is actionable then this can be looked at if you open a separate issue for it.
