### ISSUE TITLE
Search users by number of files we both have

### ISSUE THREAD

**Issue by JediMaster25** [nicotine-plus/nicotine-plus#2106]
### Describe the solution you'd like
A search option to search for users instead of files that would show the users that have most files that we also have in a descending order from most repeated files to less.

**Comment by slook** [comment]
Since the server does not offer such a function, doing such an operation client-side would create an extreme amount of network traffic which is in violation of the terms of the protocol. It would quickly get the client kicked from the server.

Whilst it is perhaps a cool idea, unfortunately the protocol's design probably doesn't allow for the implementation of the suggested feature.
