### ISSUE TITLE
Make your own protocol

### ISSUE THREAD

**Issue by JediMaster25** [nicotine-plus/nicotine-plus#2107]
### Describe the solution you'd like
Since you are constrained in the features you can offer by the SoulSeek protocol wouldn't it be better for you to offer another protocol like mldonkey or shareaza did, that let you choose which networks to use, and implement the features you want since it will be your protocol? That way users can choose whether to use one or both and the features change depending which one is used.

**Comment by mathiascode** [comment]
Nicotine+ has always been, and will always be, a Soulseek client. This idea is infeasible for various reasons:

- We don't have the resources required for something like this. Almost all of the development is done by myself in my free time. I spent almost a year learning the ins and outs of the Soulseek protocol and Nicotine+, and I no longer have the time to do this for other networks.
- It's not something I'm interested in maintaining. Soulseek already has a large feature set with various quirks to maintain, and I don't believe you can do a good (enough) job when focusing on many networks at once.
- Nicotine+ would practically have to be rewritten.

**Comment by slook** [comment]
There has oftentimes been discussion of adopting a project such as https://github.com/seeschloss/soulfind which aims to replicate the features of the official server, then at that point any desired protocol extensions would become viable.

However, it is always hoped that all future development efforts would be undertaken by the developers of all clients within the community in a backwards-compatible manor, in order to avoid the problem of network segmentation that are said to have contributed towards the demise of many other networks which used to exist in the past.

The creation of an open-source version of the protocol would be a valid (and hopefully appreciated) method of increasing long-term network resilience, for example to protect against the scenario of a takedown or other disaster faced by the official server maintainers, that would cause the network users to require a fail-over solution of some kind.

In that hypothetical scenario, perhaps even a network bridge would be desirable, to ensure the official server would always have the opportunity to recover and come back online, hence any protocol extensions implemented in the meantime would need to be developed in a manor considerate of this.

As to the primary aims of the project "Nicotine+ aims to be a pleasant, free and open source (FOSS) alternative to the official Soulseek client, providing additional functionality while keeping current with the Soulseek protocol", therefore no efforts to create a spin-off protocol shall ever be implemented within this project.
