### ISSUE TITLE
Active monitoring

### ISSUE THREAD

**Issue by JediMaster25** [nicotine-plus/nicotine-plus#2115]
### Describe the solution you'd like
Instead of having to rescan all files at startup or manually whenever a file is moved, it would be nice to have active monitoring so that it automatically rescans the files when they are moved.

Or at least have the ability to scan only the specified folders instead of everything.

**Comment by slook** [comment]
Why are your re-scans taking so long? Are any scanning related errors logged in the '[Debug] Miscellaneous' log category?

**Comment by JediMaster25** [comment]
There are many files. I'm not getting any bugs.

**Comment by slook** [comment]
A feature such as this would involve a constant strain of system resources. Afaik there is not a cross-platform method of the program being informed about changes to the filesystem, so this would require the scanner to be active all the time which it is not capable of doing.

> Or at least have the ability to scan only the specified folders instead of everything.

The scanner does only process folders that have been altered since the last scan, so it should not be rebuilding everything every time...

Please specify the filesystem type that your shares are on (ext4, NTFS, etc)?

**Comment by JediMaster25** [comment]
I've recently changed the filesystem for all my drives so I would have to test it again.

**Comment by slook** [comment]
The expected behaviour for the Scanner module is that Nicotine+ indexes only those folders which contain files that have been updated since the last scan, which means that after the second time the rescan process should usually be quite rapid, even for larger shares.

If this isn't happening on your system and it is doing a full rebuild every time then this indicates some sort of bug or configuration that needs to be accounted for, such as an unusual filesystem type or perhaps even something to do with timezone I'm not sure.
