### ISSUE TITLE
Possible technical and visual tracking of already shared files

### ISSUE THREAD

**Issue by architux** [nicotine-plus/nicotine-plus#2123]
### Describe the solution you'd like

Hello and thank you for such a useful and modern SoulSeek client. 😉
I haven't dove into the actual SoulSeek protocol, but I'd like to ask a question anyway.

There's a very useful feature available in the other P2P protocol, I mean DC++ file sharing hubs, to **display already shared files** (that a current user had already shared) **with different color** (green by default) in the search result window or panel (a list of files being found upon any possible user's search request). 💡

The obvious benefit of such a feature is **not to download those files that you already have**, not to get confused with it, no matter which filenames those files may have on the other side. Technically it might be possible by **tracking some unique hash values** of files (in the DC++ domain it's called TTH, or Tiger Tree Hashing). It should be very **useful for large shares**, where current user may not clearly remember which items one currently has or has not. Especially if one tries to collect some items available of a certain whole, and wants to **clearly and visibly distinguish** those items that one has from the others that one is interested in.

I'm not sure whether it's possible to track files in the same manner in the SoulSeek world (there are no such indications in the current Nicotine+ client GUI, at least), but I'd like to clear this up anyway. And, in case it's not very possible technically (maybe due to the protocol definition itself or some related restrictions), is there a chance in theory to implement the protocol extension (either in a form of a new plugin, or within the app)? Maybe it could be a specific feature for Nicotine+ client itself (introduced on a higher client level, not on a basic protocol level)? So that would also possibly become a neat feature to choose this client among a couple of alternatives... 👍

I'd like to know what you're thinking about it, and is it possible to make it working somehow someday. 🙏

**Comment by AtticFinder65536** [comment]
There is no checksum/authentication/encryption of protocol messages outside obfuscating username+password in login in the Soulseek protocol. Files in Soulseek are not assigned with a hash. For this feature to work there needs some way to receive the hash of a file from other peers.

It is one of the weaknesses of the Soulseek protocol IMO, as the file might be modified in transit by MITM or there may a silent tiny bit flip, or the user fixes/changes something in the files and you have no way of knowing about updated files unless they tell you about it. And being sure about duplicates like you said, knowing for sure if multiple people share the same files. Other file sharing protocols do much better here.

I think a protocol extension would be ideal and it could be implemented without any disruption to to the rest of the network, but may take some work

**Comment by mathiascode** [comment]
> or the user fixes/changes something in the files and you have no way of knowing about updated files unless they tell you about it. 

We discard any previously downloaded content if the uploader sends a different file size, unlike SoulseekQt, but unfortunately all verification is based on file size, which isn't very reliable.

> I think a protocol extension would be ideal and it could be implemented without any disruption to to the rest of the network, but may take some work

Protocol extensions have been mentioned in the past, but this isn't an area I'm willing to delve into, since the protocol is proprietary and Nir has expressed concerns about people modifying it some years ago. If an extension makes it into the official Soulseek client, I will implement it in Nicotine+.

**Comment by slook** [comment]
> Maybe it could be a specific feature for Nicotine+ client itself (introduced on a higher client level, not on a basic protocol level)?

While the suggested feature would be indeed be desirable, unfortunately implementing it on a local level without hashing would be both inaccurate (only a filename/size match) and extremely resource intensive (because for each search result the database of shared files would need to be checked for a match). and would provide only minimal benefit for most use cases.

> Protocol extensions have been mentioned in the past

There is additional discussion about this topic in https://github.com/nicotine-plus/nicotine-plus/discussions/1772 which includes more reasoning as to why extensions cannot be implemented at this time.

Thank you for your thoughtful feedback @architux please always feel free to suggest any other ideas.
