### ISSUE TITLE
Merge virtual folders with the same name

### ISSUE THREAD

**Issue by JediMaster25** [nicotine-plus/nicotine-plus#2136]
Allow sharing multiple folders with the same virtual folder name and merge them together.

**Comment by mathiascode** [comment]
This is not feasible. In order to have reasonable performance, you need a virtual name that maps to a single folder. This way, you can perform simple string manipulations on a virtual path to convert it back to a real path.

If you start using the same virtual name for multiple folders, you need look up which folder the file actually belongs to, which is far more expensive.

**Comment by JediMaster25** [comment]
fopnu does it this way and it performs very well. There is [mergerfs](https://github.com/trapexit/mergerfs) anyways, so maybe I use that.

**Comment by mathiascode** [comment]
Maybe it would perform well enough in most cases, but it's a somewhat sensitive area I'm not willing to regress on in terms of performance, especially since it was (until recently) possible to freeze Nicotine+ by queueing thousands of files at once from another client.
