### ISSUE TITLE
Some bugs in Nicotine+ v. 3.2.5

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [nicotine-plus/nicotine-plus#2184]
Nicotine+ version:  3.2.5
Operating System/Distribution: Windows 10 LTSB 2016 x64

1) No translation string for this:

![2022-09-15_23-14-11](https://user-images.githubusercontent.com/31162059/190455180-f2454e5d-4b90-4b36-bf7b-2f0cc273b2ff.png)

2) When I am trying to save settings I see this message in log:
![2022-09-15_23-16-11](https://user-images.githubusercontent.com/31162059/190455415-c21332e9-9df1-43c0-895b-cbbba393912c.png)

3) The line is always highlighted when you enter the statistics section:
![2022-09-15_22-31-48](https://user-images.githubusercontent.com/31162059/190456175-6eaff0a1-320c-435b-bb04-9947fe78e632.png)

**Comment by mathiascode** [comment]
> 1. No translation string for this:

Thanks, it's now translatable.

> 2. When I am trying to save settings I see this message in log:

Preferences -> Downloads -> Download filters -> Enable "Escape" for the *.url filter

> 3. The line is always highlighted when you enter the statistics section:

This is intentional, at least until I figure out how to focus a label without selecting it.

**Comment by SnIPeRSnIPeR** [comment]
Ok, thanks!

1) Where I can find this:
"Cannot find %s or newer, please install it."

2) Preferences -> Downloads -> Download filters -> Enable "Escape" for the *.url filter
What does it mean "escape"? Filter OFF?

**Comment by slook** [comment]
1. If GTK is not installed then the program cannot be launched so this string is printed to the terminal:
https://github.com/nicotine-plus/nicotine-plus/blob/bc15e38c08855c198e76c336564e06b4e7ed96b0/pynicotine/gtkgui/__init__.py#L45-L54

3. It means special characters are automatically escaped by the program, so that the user doesn't need to put the `\` escape characters in themselves. The technical jargon and layout of this section needs review to be more user friendly.

**Comment by slook** [comment]
> until I figure out how to focus a label without selecting it

@mathiascode Suggest another approach might be adding a Close button for the default focus to be assigned something useful.
