### ISSUE TITLE
Can't exit Room tabs when internet connection is off

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [nicotine-plus/nicotine-plus#2192]
Nicotine+ version:  3.2.5
Operating System/Distribution: Windows 10 LTSB 2016 x64

![2022-09-21_23-19-59](https://user-images.githubusercontent.com/31162059/191558202-f56821db-38ab-4249-b58c-c94afc805660.png)

**Comment by slook** [comment]
This characteristic of the blocked interface might prevent erroneous behaviour from happening later on, considering that we are supposed to tell the server we are leaving the room, otherwise we would need to queue the LeaveRoom request which doesn't seem like it would be worthwhile.

For the same reason other actions are not possible, such as sending a message.

Unless there is a good argument for leaving a room while disconnected, I think it would be better to not fix this.

**Comment by mathiascode** [comment]
> This characteristic of the blocked interface might prevent erroneous behaviour from happening later on, considering that we are supposed to tell the server we are leaving the room, otherwise we would need to queue the LeaveRoom request which doesn't seem like it would be worthwhile.

We automatically leave rooms when disconnecting, so it would be fine to simply close the tab if we aren't connected.

**Comment by slook** [comment]
What happens in the scenario where the local interface goes down and there is not an opportunity to disconnect gracefully?

**Comment by slook** [comment]
For some reason it is possible to reach a state where room tabs cannot be closed at all, even when "Online", yet the `/leave` command does still work.

Unsure how to replicate, it seemed to occur either while the machine was asleap or after the local network connection went down.

**Comment by mathiascode** [comment]
> What happens in the scenario where the local interface goes down and there is not an opportunity to disconnect gracefully?

Still counts as leaving a room. We leave a room as soon as we're no longer logged into the server for any reason.
