### ISSUE TITLE
Ability to Open Nicotine Plus in the same state as when it was closed 

### ISSUE THREAD

**Issue by MannyK2018** [nicotine-plus/nicotine-plus#2241]
### Describe the solution you'd like
During a session you may often browse an number of users files and make a number of searches. It would be useful if you could save this data down at the point of exit to use during the next session. 

### Additional context
With the problems VPN's cause with port forwarding you often have to shut the application down as part of restoring its full functionality and being able to return to the same point as where you were would save time and effort. Its quite frustrating having to redo the searches and browsing share enquiries simply because there is no save facility. Equally you don't really want to save down every users shares list onto your PC (the alternative part solution) and then manually upload them again.

**Comment by slook** [comment]
> there is no save facility

There is a feature that does exist which enables manual saving of browsed user's shares lists...

![Screenshot_2022-11-02_07-32-30](https://user-images.githubusercontent.com/88614182/199427023-f45caa2a-f8f5-4e7e-98c8-5fbb342c823b.png)

... then it is saved into the nicotine data folder for later use:

![Screenshot_2022-11-02_07-21-58](https://user-images.githubusercontent.com/88614182/199425384-e3aaeba3-ae45-4491-a899-27e183ade6cb.png)

The Browse Shares toolbar might be revised in a future version, I think it is needed to have a full width toolbar on each user page with more buttons and widgets visible on screen, because currently most of the functions are hidden only in context menus.

It's probable that automatic list saving might not have been previously desirable due to limited local storage space and some lists can be large. Perhaps it would then become necessary to prune old lists that are older than a certain age.

> It would be useful if you could save this data down at the point of exit to use during the next session.

I see, you are suggesting a feature whereby any open tabs will be automatically saved to disk? That does sound like a good idea, it would then be a bonus if such saved data is automatically rescalled upon startup. In this scenario, there would need to be a clear visual indicator that the currently viewed shares list is not nessassrily up-to-date.

In thereoy it would be possible to remember open Browse tabs in the same way as we remember open Prvate Chat tabs. The tricky part of such an implementation would be ensuring that the application doesn't produce excessive network requests upon startup, and uses at first saved local data if available.

**Comment by mathiascode** [comment]
> With the problems VPN's cause with port forwarding you often have to shut the application down as part of restoring its full functionality and being able to return to the same point as where you were would save time and effort

Wouldn't it be better to add the ability to change ports/network interface without restarting Nicotine+, simply requiring reconnecting to the server? See also: https://github.com/nicotine-plus/nicotine-plus/issues/2025

**Comment by slook** [comment]
Any sort of lazy-loading mechanism is going to be prone to issues such as unpredictable behaviours, failure to properly update from the remote peers, and unwanted background loading. Indeed it would be difficult to maintain to the point where it might not provide the intended benefits considering the effort required to implement.

Agreed it would be wiser to first implement the previously discussed in-session port-changing ability, before even considering the addition of a large set of features such as the op's suggestion would entail.

**Comment by mathiascode** [comment]
Closing in favor of implementing https://github.com/nicotine-plus/nicotine-plus/issues/2025
