### ISSUE TITLE
Idea: `slsk://` URL format

### ISSUE THREAD

**Issue by ctrlcctrlv** [nicotine-plus/nicotine-plus#2256]
### Describe the solution you'd like
When browsing shares, I'd like to be able to copy URLs of the format e.g.:

* slsk://server.slsknet.org:2242/copypaste/73.198.184.247:2235/Soulseek\tv\Q.Into.the.Storm.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]?intent=recursive

The schema would be:

```lark
// Toplevel
slsk_uri: (PROTOCOL? . PROTOSEP)? . hostport . URISEP . username . (URISEP . hostport)? . URISEP . hsegment . ("" | "?" search)

// Constants
PROTOCOL : "slsk"
PROTOSEP : "://"
FILESEP : "\\"
URISEP : "/"

// Generators
username: uchar+
search: hsegment

// Generators for URI's in general. 
// Source: https://github.com/ligurio/lark-grammars/blob/master/lark_grammars/grammars/rfc_1738.lark
hostport	: host ("" | ":" port)
host		: hostname | hostnumber 
hostname	: (domainlabel ".")* toplabel
domainlabel	: LETTER | ALDIG MIDDIG* ALDIG 
toplabel	: LETTER | LETTER MIDDIG ALDIG
hostnumber	: (DIGIT~1..3 ".")~3DIGIT~1..3
port		: natural
natural		: DIGIT | DIGIT_LEADING DIGITS
unreserved     	: LETTER | (DIGIT | (SAFE | EXTRA))
uchar          	: unreserved | unreserved | escape
hsegment	: ( uchar | (";" | ":" | "@" | "&" | "=" ))*
escape		: "%" HEXDIGIT HEXDIGIT
// Constants for generators
LETTER		: LCASE_LETTER | UCASE_LETTER
DIGIT		: "0".."9"
DIGIT_LEADING	: "1".."9"
DIGITS		: DIGIT+
SAFE		: "$" | "-" | "_" | "." | "+"
EXTRA		: "!" | "*" | "'" | "(" | ")" | ","
HEXDIGIT	: "a".."f"|"A".."F"|DIGIT
ALDIG		: /[LCASE_LETTER | DIGIT]/
MIDDIG		: /[LCASE_LETTER | DIGIT | "-"]/
```

**Comment by mathiascode** [comment]
We already have URLs in the format `slsk://username/path`, there's a menu item in the context menu to copy them.

**Comment by ctrlcctrlv** [comment]
@mathiascode really? maybe my nicotine+ is too old

**Comment by ctrlcctrlv** [comment]
oh ok no i do see that. i meant in the «Browse Shares» tab

and anyway my format is better because it is server-independent (not that this much matters lol)

**Comment by mathiascode** [comment]
It's present in all tabs that contain file lists (search, downloads, uploads, browse shares):
![](https://user-images.githubusercontent.com/8754153/201483103-8b7e2e54-1c5c-455d-a2e3-e07febff6e1b.png)

> and anyway my format is better because it is server-independent

The current format was added about 20 years ago (https://nicotine-plus.org/NEWS#version-102-august-23-2003), wouldn't be a good idea to change it anymore.

> (not that this much matters lol)

I would be surprised if someone actually started hosting another server today. :P
There's https://github.com/seeschloss/soulfind, but it hasn't been updated since 2006 or so, and has some stability issues.
