### ISSUE TITLE
Nicotine+ should automatically let user know if client is out of date and give option to disable that notification

### ISSUE THREAD

**Issue by Pentaphon** [nicotine-plus/nicotine-plus#2468]
### Describe the solution you'd like
I'd like Nicotine+ to automatically check if it needs to be updated, notify the user if it is out of date and if people don't want that, they can disable that update check.

**Comment by slook** [comment]
> if people don't want that, they can disable that update check.

I disagree. If the suggested feature were to be implemented, then it should be opt-in rather than opt-out.

**Comment by slook** [comment]
Perhaps to advertise the suggested feature, a "Automatically check for new versions" checkbox could be added to the version checker dialog (in addition to it being buried somewhere in the Preferences):

![image](https://user-images.githubusercontent.com/88614182/229147978-247574d2-50aa-4482-bf19-124dcf92dc79.png)

**Comment by Pentaphon** [comment]
> Maybe if the version increment is only a minor revision, then the alert should be only a log message (visible in the status bar shortly after startup), rather than randomly popping up an annoying Out Of Date dialog box.

I would like it to show up on the main window at the very bottom as a simple line of text. Maybe have it check every 2 weeks instead of every startup? To reduce how many times it has to check?

**Comment by mathiascode** [comment]
This would be fine on Windows and macOS. Not sure about other operating systems, since they use package managers and follow their own release schedule.

**Comment by DeathStalker77** [comment]
I think that an option to be notified of available Beta/Nightly updates would also be advantageous (especially if clicking the YES to download/install performed those functions AIO - so you don't have to manually go to the page, DL, then install.  :-)

**Comment by slook** [comment]
It's tricky because there are privacy implications for such a feature that needs to "phone home" (or even call any third-party server which is unrelated). The users certainly wouldn't want the client to track their usage.

> so you don't have to manually go to the page, DL, then install

Having any sort of built-in updater/installer exposes a potential attack surface that could make the installation vulnerable to being hijacked. Whilst it would seem very convenient, it simply isn't worth the risk.

**Comment by DeathStalker77** [comment]
That is an interesting observation.  Yes, clearly it would have to "phone home", but then again MANY (if not most) programs do this, or at least have the option.  I think that, as long as we (the users) are confident in the devs working on it, and that the DL/Update will be sourced from an OFFICIAL repo (and identify it!), then we should be good.  Otherwise, it's the same "risk" that anyone takes using OOS - you _could_ always have a malicious coder in the mix which could screw up even your main base code.  As this is often a critical function in the professional software that i help develop (as a PSPO II), I would really like to understand more about this type of possibility :-)  Thanks!!!

**Comment by slook** [comment]
Closing, there isn't a good enough reason to change the existing version checking function, since the way it currently work seems to be satisfactory for most.
