### ISSUE TITLE
Search filter: username

### ISSUE THREAD

**Issue by tomato-fred** [nicotine-plus/nicotine-plus#2537]
Hello, I think a usefull feature would be to be able to exclude search results based on username. So that appending a hyphen to a username in the search query will hide the results from such user.

Hopefully it's quite straightforward to do, unfortunately I cannot program otherwise I would be at it.

**Comment by slook** [comment]
In the [latest unstable build of Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md) 3.3.0.dev5 something similar is already implemented to work from the Include and Exclude filter entries.

To implement this into the search query entry is could also make sense I suppose, but it would be more complex.

**Comment by tomato-fred** [comment]
Having this feature in a query seems more practical to me, maybe it's just out of habit but i prefer them to filters. for example to filter out wishlist results i often add -.jpg -.mp3 and from reading other threads seems like it's quite a common practice.
How are quotation marks treated in the search? Would -"user name" work?

**Comment by slook** [comment]
There would be too many downsides of username matching in the Search Term query text entry box, so sadly it cannot easily be added there.

Closing this issue as completed, since PR #2244 username(s) can now be specified in the Inlcude/Exclude search filter text entries, this seems to be a satisfactory solution.
