### ISSUE TITLE
Do not auto-join #nicotine chat room

### ISSUE THREAD

**Issue by cl0ck-byte** [nicotine-plus/nicotine-plus#2556]
### Describe the solution you'd like
No auto-joining to #nicotine chat room.

### Additional context
The people over there are absolutely insane due to lack of Soulseek chat moderation.
In my honest opinion, it's even worse than 4chan with already relaxed rules.

**Comment by slook** [comment]
In the next release of Nicotine+ 3.3.0 disabling auto-join will be as simple as closing the chat tab, since the "Auto-join" checkbox no longer exists (instead, the open tabs are remembered).

The nicotine room shall remain joined by default upon first run, it's traditional!

**Comment by slook** [comment]
I know what you mean, but that problem is not within the remit of the devs to define the manor in which they choose to make use of the network.

> due to lack of Soulseek chat moderation

Indeed it is entirely up to the users to interact with eachother howsoever they desire (which is rare nowadays).

> I don't want to see creeps spamming racial slurs.

Functions are provided within the client to Ignore User or Ignore IP Address, and leaving a room is as simple as closing the room tab (which in upcomming versions the "Auto-join Room" checkbox no longer exists and is set simply by what tabs are left open).

The default room has existed for over 20 years, that will not probably not ever be changed.
