### ISSUE TITLE
Ubuntu PPA instructions could improve.

### ISSUE THREAD

**Issue by bernd-wechner** [nicotine-plus/nicotine-plus#2603]
### Describe the bug

Ubuntu PPA instructions could improve. As it stands, they don't work really.

### Expected behavior

Following the instructions here:

https://nicotine-plus.org/doc/DOWNLOADS.html#ubuntudebian

work smoothly.

### Steps to reproduce the bug

Follow those instructions on any recent Ubuntu derived system.

### Additional details

1. The command `sudo apt update` should really precede `sudo apt install`
2. The PPA is not signed. Suggest signing it and adding the command to import the public key, but in lieu of that I think this works more or less:

```
sudo add-apt-repository 'deb [trusted=yes] https://ppa.launchpadcontent.net/nicotine-team/stable/ubuntu jammy main'
```

**Comment by mathiascode** [comment]
> 1. The command `sudo apt update` should really precede `sudo apt install`

Added before the first install command. My understanding is that add-apt-repository does this automatically since Debian 10, so I didn't add it before the second command.

> 2. The PPA is not signed. Suggest signing it and adding the command to import the public key, but in lieu of that I think this works more or less:

What distribution and version are you using? We used to include the command for adding the PPA key (https://github.com/nicotine-plus/nicotine-plus/commit/3da8dd2febc7b2bbf0ee08da6ab39b8651dcb94b), but I assumed this was already done by add-apt-repository. Of course it's possible that I overlooked something.

**Comment by bernd-wechner** [comment]
Using Mint 21. add-apt-repository didn't do an update or add a key.

**Comment by mathiascode** [comment]
Does `add-apt-repository 'deb https://ppa.launchpadcontent.net/nicotine-team/stable/ubuntu jammy main' --update` work?

**Comment by mathiascode** [comment]
Added the -u option in a066522bb639614a69be062dd75afbbe99e6c4de. I still need to verify if the key is added in Linux Mint (works in Debian 12 and Ubuntu 22.04 at least).

**Comment by mathiascode** [comment]
Turns out Linux Mint provides its own add-apt-repository command, which doesn't support the -u option (it's in the mintsources package) and doesn't add PPA keys unless you use the ppa: syntax. I've updated the instructions to work around this.
