### ISSUE TITLE
Can you swap "close" and "reset" buttons?

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [nicotine-plus/nicotine-plus#2678]
Can you swap these buttons? Typically, the "close" button is in the far right position. There is a risk of clicking on “reset” statistics!

![2023-10-10_03-43-37](https://github.com/nicotine-plus/nicotine-plus/assets/31162059/368b4e95-d28c-4e3b-9c21-de285a0370b8)

Nicotine+ 3.2.9
WIndows 10 x64 LTSC 21H2

**Comment by slook** [comment]
However, the default focus is wrong. The Reset action should not be activated on hitting the enter key in this dialog.

**Comment by mathiascode** [comment]
The default button in the confirmation dialog is now "No".

In 3.3.0.dev5, the close and reset buttons are now on the opposite side of the window, due to the fact that it's easier to share the layout in both the headerbar and non-headerbar modes of the application.

The button layout probably isn't ideal on all platforms, but I'll close this issue since there's no longer a large risk of resetting your statistics.
