### ISSUE TITLE
Show total folder size on search tab

### ISSUE THREAD

**Issue by oTalDoNexus** [nicotine-plus/nicotine-plus#2697]
First of all, thanks for the amazing project..

So my feature request is that we could be able to show the total folder size, since we can just see their size individually, i was searching for that on official SoulSeek but couldn't find it and by search i just found Nicotine and i like it a lot! Thanks in advance

**Comment by slook** [comment]
It would only be possible to display the total size of whichever files that are displayed from each folder, not all of the files that might be in each folder (because that would involve making a FolderContentsRequest to every individual peer after getting the results, which is not allowed on the protocol).

**Comment by mathiascode** [comment]
In Nicotine+ 3.3.0, you will be able to select a folder row in search results -> File Properties, and the total size of the visible files will appear in the title of the file properties dialog.

For search results where the whole folder isn't displayed, when https://github.com/nicotine-plus/nicotine-plus/issues/1659 is implemented in the future, we could show the total size of the folder there.

**Comment by mathiascode** [comment]
Closing in favor of #1659
