### ISSUE TITLE
Allow N+ to update Port without restarting

### ISSUE THREAD

**Issue by DeathStalker77** [nicotine-plus/nicotine-plus#2704]
### Describe the solution you'd like
One should be able to change the Port, hit Apply, and the change will automatically take effect without having to close and restart the program.

### Additional context
MANY other programs (ex, qBittorrent, uTorrent, etc) have this functionality.

**Comment by mathiascode** [comment]
Doesn't matter which programs have this functionality or not. Due to the way the Soulseek protocol works, changing the port requires a server reconnect.

At present, this can be done by selecting Menu -> Disconnect, then Menu -> Connect. If this should be done automatically or not is the question, since it would interrupt downloads/uploads for a moment.

**Comment by DeathStalker77** [comment]
Ok, once you get into the details of protocols, then you lose me :-D   I know TCP & UDP, and I only understand the basics of their functionality, not the technical details.  Have you had a chance to review those links I posted regarding multiple apps using the same port yet?  The technical aspects of them are, again, beyond my understanding.

**Comment by slook** [comment]
> If this should be done automatically or not is the question, since it would interrupt downloads/uploads for a moment.

From the users point of view, an automatic reconnection would be trivial, in most cases it would hardly be noticed.

**Comment by JurgenR** [comment]
> Doesn't matter which programs have this functionality or not. Due to the way the Soulseek protocol works, changing the port requires a server reconnect. This isn't something we can change.

There doesn't seem to be a restriction on how many times the `SetWaitPort` message is sent, the server will accept it and return the correct ports when `GetPeerAddress` is called for the user. Is there perhaps some other limitation?

**Comment by mathiascode** [comment]
> > Doesn't matter which programs have this functionality or not. Due to the way the Soulseek protocol works, changing the port requires a server reconnect. This isn't something we can change.
> 
> There doesn't seem to be a restriction on how many times the `SetWaitPort` message is sent, the server will accept it and return the correct ports when `GetPeerAddress` is called for the user. Is there perhaps some other limitation?

I don't remember how Soulseek NS and SoulseekQt behave, but Nicotine+ caches the IP address and port of a user until they go offline, which would break things.

**Comment by slook** [comment]
So in other words, a local port change whilst continuously connected is technically possible, but it is worthless because peers won't be notified about it until we reconnect?

**Comment by JurgenR** [comment]
> So in other words, a local port change whilst continuously connected is technically possible

It should be. The actions would be to:

* disconnect the old listening ports
* connect the new listening ports
* notify the server of the new listening ports through the `SetWaitPort` message
* (you'd have to deal with remapping ports using UPnP here as well)

> but it is worthless because peers won't be notified about it until we reconnect?

I don't like the choice of words here. If a client always requests the peer address / ports (through `GetPeerAddress` message) when attempting to connect to another peer then there is no problem, since the server will return the updated ports and those should be used to make a direct connection. But like @mathiascode said, if a client implementation caches the responses for `GetPeerAddress` then that client will attempt to connect using the older cached ports. If indeed this cache is only cleared when a peer goes offline then it won't be possible anymore to make a (direct) connection to that peer for as long as he hasn't reconnected.

The caching could be removed and it would make changing the port on the fly possible, but since there's already versions out there that would still do caching it would be tricky. It would mean removing the caching, waiting until everyone has upgraded and only then allowing to change ports on the fly.

It's a decision to make: you could just remove the caching and allow it; it might cause minor issues for some people, but what percentage of people would be changing their ports on the fly? Or you could start with removing the caching and deal with it later when older versions are slowing fading. Or it might not be worth doing, but keep in mind here that since it is technically possible that other clients might allow changing the port and there could be some minor issues.

**Comment by mathiascode** [comment]
In Nicotine+, we need to cache IP addresses when ignoring chat messages by IP, to avoid excessive GetPeerAddress requests to the server. For direct connections however, assuming the official clients don't cache any IP addresses, we could make an exception and always ask the server for the current IP address:port of a user.

Do you remember if the official clients always send a GetPeerAddress message to the server before connecting to a user? If not, I could verify later.

**Comment by JurgenR** [comment]
From a quick check in QT it does look like there might be some caching going on. However it might be better if you double checked.

The check was: request user info from a user, wait until connection has timed out, request user shares from the same user again. `GetPeerAddress` was only requested on the initial connect. User was in the user list (not sure if this would make a difference).

_Initial_

```
Send PM_USER_INFO_REQUEST message to user <USER>
   Did not find messaging connection to user, queueing unsent message
Attempting peer connection of type P to user <USER>
   Also sending indirect connection request.
   User address not found, requesting address
User <USER> address arrived
   Attempting direct connection of type P
```

_Second_

```
Send PM_GET_SHARED_FILE_LIST message to user <USER>
   Did not find messaging connection to user, queueing unsent message
Attempting peer connection of type P to user <USER>
   Also sending indirect connection request.
```

**Comment by mathiascode** [comment]
> From a quick check in QT it does look like there might be some caching going on. However it might be better if you double checked.

The "User address not found" part of the log message would seem to suggest that. I'll take a look soon.
