### ISSUE TITLE
"edit share" missing a browse button

### ISSUE THREAD

**Issue by sysdbugfactory** [nicotine-plus/nicotine-plus#2762]
Nicotine+ version:  3.2.2
Operating System/Distribution: debian 12.2 / kde

### Describe the bug

when editing a shares there is no option to browse the drive to find a directory. one can only manually type to change the path which seems odd.
to be able to access a browse functionality one has to remove the share then click add to make a new one which starts again from the home folder instead of the share location.

### Expected behavior

having a browse button which open a file browsing window from the path of the share to be able to navigate from there.

### Steps to reproduce the bug

open nicotine, go to the shares preference window in ont of the duplicate way to do it, select a share and click the edit button.

**Comment by mathiascode** [comment]
I'm not quite sure what you're trying to do. The only thing you can change in the edit dialog is the virtual name of a share, not the path.

Are you asking for a way to open a shared folder in the file browser (i.e. just for browsing the contents, no intention of sharing another folder), or in the file chooser, so you can add more shared folders located nearby?

Would it help if the "Add" button remembers the last location that was chosen the file chooser, instead of showing the home folder?

**Comment by slook** [comment]
> Would it help if the "Add" button remembers the last location that was chosen the file chooser

More helpful would be the parent folder one level up, unless it's at root, because it is somewhat likely that the next share to add will be somewhere nearby, but probably not inside the previously added shared folder.
