### ISSUE TITLE
Copying search result filenames causes crash

### ISSUE THREAD

**Issue by metaisfacil** [nicotine-plus/nicotine-plus#2781]
Nicotine+ version:  [Latest unstable](https://github.com/nicotine-plus/nicotine-plus/actions/runs/7129639514#artifacts)
Operating System/Distribution:
Windows 10

### Describe the bug
Selecting a file in downloads, uploads, or searches and pressing Ctrl+C to copy the file name to clipboard will immediately crash the program.

### Expected behavior
Filename should be copied to clipboard. The program should not crash.

### Steps to reproduce the bug
1. Perform any search, or switch to either the "Downloads" or "Uploads" tab.
2. Expand any folder in the chosen list, then select one of its files.
3. Press Ctrl+C.

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment]
Cannot replicate using the reproucer steps provided.

What sort of crash is it silent or is there a Critical Error dialog with a stack trace?

**Comment by mathiascode** [comment]
Does it only happen when filtering? What about other lists such as downloads/uploads, does Ctrl-C work fine there?

**Comment by mathiascode** [comment]
> I installed [this build](https://github.com/nicotine-plus/nicotine-plus/actions/runs/7182646995). Copying files _**no longer**_ crashes the program,

Thanks for testing. Could you try [this build](https://github.com/nicotine-plus/nicotine-plus/actions/runs/7174673532) (before the clipboard-related changes were made) and the newer build back-to-back, to confirm if the bug is actually fixed, or if it happened to go away temporarily.

> ~however it's not copying the file name to clipboard, just "0".~ It now appears to be working properly, no idea why it was only copying "0" before.

"0" would be one of the empty numerical columns.

**Comment by mathiascode** [comment]
> Alright, I've realized Ctrl+C will copy whichever specific part of the line was last clicked. I was not aware of this nuance, is it intended behavior?

That's intended. The exact value of the focused cell is copied. You can see which cell is focused by holding Alt, and move focus to another cell by either clicking it or using the arrow keys.

> if I click the music icon, Ctrl+C copies "audio-x-generic-symbolic"

Thanks for mentioning this, it should now copy the tooltip text instead.

> and previously if I clicked any blank areas under the "Folder" column to the left of the filename, Ctrl+C would cause the crash. I can't get the newer build to crash this way.

Ah, that would explain it. An empty string used to be copied to the clipboard, which must've caused a crash for some reason.

Since the crash no longer occurs, I'll close this issue. Let me know if you run into any other issues.
