### ISSUE TITLE
Browse Shares: folder downloads should always be recursive

### ISSUE THREAD

**Issue by stefantalpalaru** [nicotine-plus/nicotine-plus#2812]
The first two options on the right click menu in the folder view are almost never what the user wants, because they do not download subfolders (which usually have artwork, or individual CDs). I propose we remove them and rename the next two options to remove "& Subfolders".

This will simplify the interface, make it more intuitive and protect the user from discovering this footgun the hard way.

In the off chance that someone actually wants to download only the top-level files in a folder, without subfolders, it would still be possible - by using the file view, on the right.

**Comment by mathiascode** [comment]
> This will simplify the interface, make it more intuitive and protect the user from discovering this footgun the hard way.

There's another footgun as well: recursively downloading a root folder of a huge share. This is even worse in SoulseekQt, where it's too easy to accidentally double-click a root folder, start a recursive download, and end up freezing the client.

**Comment by stefantalpalaru** [comment]
> recursively downloading a root folder of a huge share

Not something users need protecting from, since it requires right-clicking and selecting a menu option.

**Comment by mathiascode** [comment]
> > recursively downloading a root folder of a huge share
> 
> Not something users need protecting from, since it requires right-clicking and selecting a menu option.

I disagree. I've had incidents in the past where the first item of a menu was selected by accident (although it shouldn't happen as often in the GTK 4 version due to the additional padding in menus). It would also be helpful to have a confirmation dialog if a subfolder is larger than expected, in my opinion.

The file limit should be large enough that users don't see the confirmation dialog when downloading a reasonable number of folders at once. I've set it to 1000 in my PR for now, but we can change this if necessary.

**Comment by stefantalpalaru** [comment]
> It would also be helpful to have a confirmation dialog if a subfolder is larger than expected, in my opinion.

Oh, yeah. Good idea.

**Comment by DarkVoyage** [comment]
I'd like to see something like this dialog in N+, when you download folder and subfolders.
![image](https://github.com/nicotine-plus/nicotine-plus/assets/31579340/8654bfaa-4f2b-496b-a28f-c4be93f9aa69)

**Comment by slook** [comment]
It was being worked in PR https://github.com/nicotine-plus/nicotine-plus/pull/2538 but unfortunately the contributor abandoned the development branch before it was finished.

**Comment by mathiascode** [comment]
I think the download dialog is fine for search results, but the file list seems redundant when browsing shares.

Here's an attempt at fitting the pieces together:

### Folder Treeview

Two download options:
- Recursively download folder: downloads the original folder recursively without additional steps, but asks for confirmation if a very large number of files will be downloaded
- Recursively download folder to: shows a small dialog allowing you to set the folder name of the root folder, where to download to, as well as a toggle to specify if the download should be added in paused mode

### File List

Two folder download options:
- Download folder (not recursive): downloads the folder without additional steps
- Download folder to (not recursive): shows a small dialog allowing you to set the folder name, where to download to, as well as a toggle to specify if the download should be added in paused mode

Two file download options:
- Download files: downloads the selected files without additional steps, saves them in the original folder instead of the root of the download folder
- Download files to: shows a small dialog allowing you to set the folder name (leave empty to restore original behavior of downloading directly to the root of the download folder?), where to download to, as well as a toggle to specify if the download should be added in paused mode

Search results would probably be similar, except the dialog contains a list of all files in the folder that you can select. Should revisit this.

**Comment by DarkVoyage** [comment]
Also one unintuitive thing (this is not what should be repeated from SoulseekQt) that you see only files, not folders in right pane.
It looks like folder and whole tree is empty. I'd like to see folders on top, like in any file browser and you can double-click them to go deeper.
![image](https://github.com/nicotine-plus/nicotine-plus/assets/31579340/f2c2ba96-e14c-4e4b-8a00-678002fea777)

**Comment by stefantalpalaru** [comment]
My initial request was covered by https://github.com/nicotine-plus/nicotine-plus/commit/5427c5ec212789c6433493df45457f78f3c200bd

We can close this issue, unless it serves to track additional improvements.

**Comment by mathiascode** [comment]
Unlikely to make any larger changes to the layout unless several people ask for it.

Download dialog is covered by https://github.com/nicotine-plus/nicotine-plus/issues/1659
