### ISSUE TITLE
Nicotine 3.3.0 Flickering when changing tabs

### ISSUE THREAD

**Issue by puppeht** [nicotine-plus/nicotine-plus#2859]
Nicotine+ version: 3.3.0
Operating System/Distribution: Windows 10 Pro Version 10.0.19045 Build 19045

### Describe the bug
The display will flicker black when changing tabs in the client, clicking buttons or opening a menu.

### Expected behavior
The display won't flicker when performing these actions.

### Steps to reproduce the bug
Open Nicotine client. Click on Downloads tab, display flickers.

### Additional context
Screenshots, logs, stacktraces or relevant information.
https://streamable.com/j3g8dp
Video recorded on my phone as my display capture in OBS will not capture the flickering. Instead, the recording goes black.
Hardware: Ryzen 7 5800x3d, 5700XT
Flicker happens both on primary monitor (HP Omen 27q) and secondary monitor (D2719HGF)
Have tried restarting PC, repairing Nicotine+, and reinstalling to no avail.
Graphics drivers are updated to 24.1.1.

**Comment by slook** [comment]
What happens when you unmaximize the window?

**Comment by puppeht** [comment]
It does not flicker while unmaximized.

**Comment by slook** [comment]
What is GTK version in Menu > Help > About Nicotine+ ?

**Comment by puppeht** [comment]
GTK version is 4.12.5

**Comment by slook** [comment]
Why is the Windows Taskbar not visible in your video? Have you hidden it on purpose or is Nicotine+ running in some sort of native fullscreen mode?

**Comment by puppeht** [comment]
The taskbar is hidden when not in use.

I do not believe my graphics drivers think it's a game.

**Comment by slook** [comment]
Can you repeat the test with some active Search Files tabs and populated Downloads and Uploads, does the flickering still occur in this case or not?

**Comment by puppeht** [comment]
The flickering still occurs with active searches and downloads.

The flickering persists regardless of monitor connections.

**Comment by slook** [comment]
Does it happen on other Windows machines?

**Comment by matterharz** [comment]
Nope. Not even with the taskbar hidden.

**Comment by litemotiv** [comment]
I have similar issues with these N+ and GTK versions, which i believe may be related to the same bug and possibly #2779.

At the first N+ start, the window will often freeze, i can often trigger it directly when i press the window maximize or minimize button. If it doesn't freeze completely, the screen may shortly become black when switching tabs or window modes, as mentioned in the first post. 

The screen may stay frozen until i bring up the taskmanager (via ctrl-alt-del), at which time the screen unfreezes immediately. After this has occurred, the N+ window functions normally without further issues.

This happens on a new Win 11 laptop i just installed. Also with the windows taskbar auto-hidden. 

Another factor may be that the display zoom factor is set to 250% (by default) due to the resolution of the screen.

**Comment by slook** [comment]
Thank you all. Can someone verify if the flickering only occurs when the Windows Task Bar is set to auto-hide?

**Comment by matterharz** [comment]
Yeah.

**Comment by slook** [comment]
@puppeht Please can you isolate that the flickering is only occurring when the Windows task bar is set to audo-hide?

**Comment by matterharz** [comment]
> Does disabling Client Side Decorations (in Preferences > User Interface > Use Header Bar > Off) avoid the flickering?

It does.

**Comment by slook** [comment]
The bug probably belongs to GTK, but I can't find which one.

**Comment by DeathStalker77** [comment]
I have not noticed the flickering (Win10)

**Comment by litemotiv** [comment]
> Thank you all. Can someone verify whether or not if the flickering only occurs when the Windows Task Bar is set to auto-hide?

@slook i can confirm the bug is absent when the taskbar is set to always be visible (no auto-hide).

**Comment by mathiascode** [comment]
It's probably an issue in the GPU renderer, I remember seeing some GTK issue about flickering in some cases. Since there are more issues here (someone on Windows reported that the window is invisible), and GTK devs are working on [new GPU renderers](https://blog.gtk.org/2024/01/28/new-renderers-for-gtk/), I would rather not spend time debugging this right now.

The following build forces the Cairo software renderer (same as previous Nicotine+ versions), does it work better? Scroll down for download links: https://github.com/mathiascode/nicotine-plus/actions/runs/7802021701

**Comment by litemotiv** [comment]
> The following build forces the Cairo software renderer

This version works fine, the bug doesn't occur. 

The screen redraw feels more responsive overall as well.

**Comment by slook** [comment]
Then shall it be a good idea to switch the Windows builds to Cairo for now, until the upstream GTK bug in hardware acceleration related to the GPU rendered is fixed?

**Comment by mathiascode** [comment]
3.3.1.dev1 now uses Cairo on Windows: https://nicotine-plus.org/doc/TESTING.html#windows

@puppeht @matterharz Could you check if the issue is fixed for you too?

**Comment by matterharz** [comment]
It's fixed for me.

**Comment by puppeht** [comment]
Yes, this seems to be fixed.

**Comment by slook** [comment]
@DeathStalker77 Are you able to verify that the switch to software rendering doesn't cause any noticeable performance regression under heavy load in the latest 3.3.1dev1 build?...
https://nicotine-plus.org/doc/TESTING.html#windows

**Comment by DeathStalker77** [comment]
I will check over the weekend with the latest build at that time!  (Slammed IRL right now with new project :( )

--- DS

**Comment by DeathStalker77** [comment]
No flicker on Win10, all updates, GTX1080i - though i _**am**_ down to less than 28k files now :D  (from a max of over 160k!!!)

--- DS

**Comment by DeathStalker77** [comment]
Most I have currently in one list is ~5600 and no issues scrolling up & down that either manually or via scrollbar.

It will need to wait a bit before I can jack things back up to over 100k! :-D

--- DS
