### ISSUE TITLE
Horizontal adjustment of user profile

### ISSUE THREAD

**Issue by woollarding** [nicotine-plus/nicotine-plus#2865]
Nicotine+ version:  3.3.0
Operating System/Distribution: Windows 10

### Describe the bug
No longer able to adjust the user profile columns horizontally  

### Expected behavior
when floating cursor over vertical dividers should get a <-> and be able to adjust horizontally 

### Steps to reproduce the bug
try to adjust columns 

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by woollarding** [comment]
i guess its not 100% necessary, some of the more verbose profiles are just
easier to read in a wider column .. it worked before so i reported it

**Comment by slook** [comment]
Removed bug label, since changing to a responsive layout based on main window size was an intentional change so that the interface is usable on narrow width viewports.

Admittedly, you raise a valid point since most users don't have a picture and when their is text then it can sometimes be large. I feel like might be good to swap it around, or restore the movable separators as before when the layout is not vertically stacked.

**Comment by woollarding** [comment]
Or maybe if it's possible enable/disable a column .. definitely not a
priority
