### ISSUE TITLE
Unable to type to search download/upload lists on macOS Monterey

### ISSUE THREAD

**Issue by thep50** [nicotine-plus/nicotine-plus#2927]
Nicotine+ version:  3.3.3.dev1
Operating System/Distribution: macOS Monterey 12.7.3

I've noticed that in all the versions since 3.3.0 I've been unable to search my download & upload lists by typing while either tab is selected. I see that on latest Windows version it does work and shows a search bar at the bottom, but no search bar appears on Mac. Though this function has been working on Mac on the wishlist window, but sometimes it too fails but is fixed after closing and reopening Nicotine+.

**Comment by slook** [comment]
Which GTK version is displayed in Menu > Help > About Nicotine+

**Comment by thep50** [comment]
4.12.5

**Comment by slook** [comment]
Can you confirm that the Ctrl+F (or Cmd+F_ shortcut works to initiate the text search, and it is only a failure of starting to type the term that fails?

**Comment by thep50** [comment]
Ah, so Cmd+F doesn't do anything, but Control+F brings up the bar.

**Comment by slook** [comment]
Control+F is the intended method to begin finding text using the widget built-in to the TreeView.

The fact that it can sometimes be started by typing characters is a bonus, but it depends on which widget is focused. You can't search for things beginning with "R" or "T" (which are shortcut keys for Retry and Stop) like that, unless you press Control+F beforehand.

It won't be improved, because we'd rather put effort into a proper data filtering/finding solution instead of using the one that comes with GTK.
