### ISSUE TITLE
Nicotine+ affected by recent update of antivirus?

### ISSUE THREAD

**Issue by thep50** [nicotine-plus/nicotine-plus#3059]
Nicotine+ version:  3.3.4 / 3.3.5dev1
Operating System/Distribution:  Windows 11 Pro

Today there was an auto-update to my antivirus software Bitdefender. I closed Nicotine+ while it was updating and right after re-opening it after the update finished, I noticed all my uploads were transferring at a much higher speed than I've ever seen them reach - hundreds of mbps per user. It would go like this for 10 seconds and then the transfers would freeze, after which Nic+ would slow down considerably, eventually completely freezing along with my system, and then I would hear some beeping sounds from my speakers, right before Nic+ finally closes.

My actual upload speed is only 30mbps, and I've only ever seen my total upload speed max out at around 6mbps, while I've had 'unlimited upload speed' selected all the time I've used it - same as on my Mac where I also run Nic+. (Bitdefender on my mac was also auto-updated at the same time, but no issues happened afterwards.)

I initially had 3.3.5dev1 installed when this first happened, so I uninstalled and reinstalled 3.3.4, but the same process happened again. I decided to set an upload speed limit, setting it to my usual total max speed, but I noticed after doing this, every user's transfer speed is the exact same most of the time, which I'm not sure I've seen before. It doesn't freeze right away after doing this, but twice now Nic+ has eventually frozen and closed in the same manner after having transfers going for a while.

I've tried disabling Bitdefender before opening Nic+ but the speed still reached above normal after raising max the upload speed.

**Comment by thep50** [comment]
Update, It seems like my uploads aren't completing anymore. They will get to 100% and the upload speed freezes, and after a few seconds it says Getting Status, before switching to Transferring again, but the completion goes down a certain percentage and it downloads until 100% again but then gets stuck in the same loop indefinitely.

**Comment by mathiascode** [comment]
Please [enable debug logging](https://nicotine-plus.org/doc/DEVELOPING.html#debug-logging) (all categories), capture the behavior in the log, and send the logs to my email address on my GitHub profile. Also mention which uploads are stuck.

**Comment by slook** [comment]
@thep50 Are you still experiencing this issue in the [latest development build](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows) of Nicotine+ 3.3.5.dev2?

**Comment by thep50** [comment]
Yes, still the same issue after trying that build. Except now when I have my upload speed limited, every single upload is stuck at exactly the same speed almost the entire time, more so than before. Unlimited speed still goes way above what it should.

**Comment by thep50** [comment]
Actually after having it open for longer, the upload speeds eventually stopped being so synced, so looks the same as before overall.

**Comment by slook** [comment]
Have you experienced any stuck/looping transfers with the new build?

**Comment by thep50** [comment]
> Have you experienced any stuck/looping transfers with the new build?

Yes, there has still been looping on the new build.

Also, since before this build I've noticed many uploaded files/folders reaching 100% and then getting stuck on queued, as it moves onto uploading the next file/folder. I've messaged some users about this and they say the uploads completed on their end.

**Comment by slook** [comment]
Okay, thanks. Please gather another round of [debug logs](https://github.com/nicotine-plus/nicotine-plus/issues/3059#issuecomment-2230325436) as before and email them to Mat if you can.

**Comment by thep50** [comment]
will do.

**Comment by mathiascode** [comment]
> Also, since before this build I've noticed many uploaded files/folders reaching 100% and then getting stuck on queued, as it moves onto uploading the next file/folder. I've messaged some users about this and they say the uploads completed on their end.

To clarify, do the uploads look like finished ones, but the status says "Queued" instead of "Finished"? Does changing to another tab and back fix the issue? The logs look normal for a finished transfer.

The one upload that looped, it seems like the transfer connection was interrupted/closed, and the user's client retried the download. Hard to say why that happened, but the response to that situation looks normal in these logs at least.

**Comment by thep50** [comment]
> To clarify, do the uploads look like finished ones, but the status says "Queued" instead of "Finished"? Does the status change from "Transferring" to "Queued"? Does changing to another tab and back fix the issue? The logs look normal for a finished transfer.

Yes, they look finished but just go from Transferring to Queued. Eventually they change to Cancelled or User Logged Off. Changing tabs doesn't fix it.

> The one upload that looped, it seems like the transfer connection was interrupted/closed, and the user's client retried the download. Hard to say why that happened, but the response to that situation looks normal in these logs at least.

Well it seems with either of these issues, uploads are being received fine on the other end. I think the main thing is it looks like my client's upload speed can get faster than the actual upload speed the user on the other end sees. This would be why when I set to unlimited upload speed, it gets to hundreds of MiB/s and finishes large files instantly, which shouldn't be possible with my ISP's actual upload speed.

**Comment by slook** [comment]
May I hypothesize to suggest I think it is indeed probable that the third-party software (Bitdefender) is running as a privileged service within the networking stack of your operating system which is initially consuming outbound network packets locally (hence why it is very fast), then doing some kind of scanning/processing on those data (no way of knowing what since all your host softwares are closed-source) before finally dispatching the intercepted data packets to the intended destination (i.e. the peer you're uploading to).

This is not a recommended configuration for any type of peer-to-peer communications, and as such, Nicotine+ was not designed to be run under such an environment. Ideally, you should try to establish a direct uplink to the peer socket with nothing else in the middle. Consider either adding the Nicotine+ executable as an exception in Bitdefinder, or uninstalling Bitdefender.

**Comment by thep50** [comment]
Fair enough. I did try allowing the Nicotine+ executable as an exception, but no change. I'd rather keep Bitdefender, so I'll just keep things working as is. Thanks for the help though.

**Comment by slook** [comment]
> I did try allowing the Nicotine+ executable as an exception, but no change

No surprise, since Nicotine+ simply delegates socket handles to the Python interpreter runtime library (but I wouldn't suggest allowing an exception for all Python scripts, that would be asking for trouble!).

Thank you for reporting the issue, it's good to know that everything else generally seems to be working well enough on your platform. 

Please do let us know if you notice anything else that requires attention while testing the 3.3.5 [development builds](https://nicotine-plus.org/doc/TESTING.html#windows).
