### ISSUE TITLE
Arrow key shortcuts to expand/collapse groups

### ISSUE THREAD

**Issue by TetroniMike** [nicotine-plus/nicotine-plus#3060]
### Describe the solution you'd like

I would like the ability to use the arrow key Left and Right buttons to expand/collapse the currently selected group(s) of content (e.g. downloads, uploads, search results, and so on, denoted by **>** ("collapsed and can be expanded") or **˅** ("expanded and can be collapsed") on the left). Currently one must click the **>**/**˅** button to expand/collapse groups of content, which takes extra time when otherwise navigating the UI via keyboard.

### Additional context

The official Soulseek client has this feature, let's port it over!

**Comment by slook** [comment]
Thank you for reminding me, I have been meaning to implement this in the same way as I did in Browse Shares.

However, I'm not rushing into it because I think at some point in the future we might be getting an entirely new widget to replace the current Gtk.TreeView widget. I'm hoping it will have left and right cursor keys out-of-the-box, but this is not for sure so nevertheless this does indeed need to be considered for the implementation.
