### ISSUE TITLE
Installation on Window 7 successful but N+ fails on start

### ISSUE THREAD

**Issue by kingleo1** [nicotine-plus/nicotine-plus#3076]
Nicotine+ version:  3.2.8
Operating System/Distribution: Windows 7

### Describe the bug
Installed successfully.
On start, this error message appears. https://i.imgur.com/bOQ5Apw.jpeg

### Expected behavior
To open the software

### Steps to reproduce the bug
Install 3.2.8 on Windows 7, then start.

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment]
Try Nicotine+ 3.2.9 https://github.com/nicotine-plus/nicotine-plus/releases/tag/3.2.9

**Comment by kingleo1** [comment]
Thank you for the suggestion. 
Uninstalled 3.2.8 and installed 3.2.9 successfully. 
Same error on startup.

Do I need to install Python? Is this related to language setting on Windows 7?

**Comment by slook** [comment]
> Do I need to install Python?

No, afaik the package includes the needed Python runtime library.

> Is this related to language setting on Windows 7?

Yes, it does look like the problem has to do with language or locale settings. What is your system's language?

Suggest trying EN_US (English, United States) to see if it runs without translation?

**Comment by kingleo1** [comment]
Removed all system languages (Eng-UK and Arabic). Installed Eng-US. Restarted.
Same error!

**Comment by mathiascode** [comment]
Doesn't look like a locale-related issue. ctypes fails to initialize:
https://github.com/python/cpython/blob/31302f5fc24eecd693f0c8aaba7c2840b09b594d/Lib/ctypes/__init__.py#L374

Does your Windows 7 installation have all updates installed, including SP1? If so, there isn't much we can do here, since Windows 7 and Nicotine+ 3.2.x are EOL, and we have no way of generating builds for them anymore.

**Comment by mathiascode** [comment]
Closing, since there's nothing we can do on our end.
