### ISSUE TITLE
Files deleted on quit

### ISSUE THREAD

**Issue by polsvoice** [nicotine-plus/nicotine-plus#3152]
Nicotine+ version:  3.3.5
Operating System/Distribution: Garuda GNU/Linux

So, I recently lost *all* of the files stored in the root of my downloads folder. I'm using the same folder for finished downloads, incomplete downloads, and received files, and it is also shared. To test this, I placed an empty file in the root, shut down Nicotine+, and it disappeared. Then, I renamed my settings folder to set everything back to defaults, and sure enough, the empty file is still there when I shut down Nicotine+.

This problem only cropped up when I reinstalled my system for some reason. I'm still using the same settings I've used for years with no problem.

**Comment by slook** [comment]
A function was recently added to remove left over files from the incomplete downloads folder. It seems to have been overlooked that this same folder might also be used for other purposes, as you have unfortunately discovered. Thank you for reporting the issue.

**Comment by mathiascode** [comment]
Ugh, I'm very sorry this happened. Looks like I forgot about cases where the incomplete folder is shared with another folder.

I'll prepare a fix for 3.3.6.

**Comment by pobgithub** [comment]
I just figured out this too, lost a bunch of files as I was sharing the download folder with my normal download folder

**Comment by slook** [comment]
@mathiascode Pin this, important issue.

**Comment by mathiascode** [comment]
I'm releasing 3.3.6 later today, but I'm short on time. @slook could you help finalize the release notes?

**Comment by slook** [comment]
@mathiascode Done.

@polsvoice @pobgithub Please test the latest build to verify that the problem is avoided in Nicotine+ 3.3.6.rc1 without any unexpected side-effects: https://nicotine-plus.org/doc/TESTING.html

> you should have a way to notify all users within the application

That was the original intent for the auto-joined "nicotine" room I suppose, but nowadays for several years general discussions overwhelm it such that any important announcements would tend to get lost in the noise... This repo is the best channel we have for this purpose at the moment, so you may wish to subscribe to GitHub notifications or follow certain issues in this repo to see if there's anything outstanding that might affect you or any matters you can help with. More testers would be ideal and much appreciated. If there's something which you feel may end up being missed then we don't mind duplicate bug reports and general queries are always welcome if you have any questions or concerns.

Anybody running `3.3.5` or `3.3.6.dev` whose 'incomplete folder' is set to the same path as the 'complete folder' can avoid encountering this bug by force-terminating (kill) rather than quitting normally, then upgrade to `3.3.6.rc1` or `3.3.6`.

**Comment by mathiascode** [comment]
> In an instance like this once it's been identified you should have a way to notify all users within the application. I spent hours trying to figure out why my files were disappearing thinking it was a Windows issue.

It's something we should consider adding in Nicotine+ 3.4.x. We try to ensure serious issues like this never happen, but unfortunately oversights will happen at some point.

I think the best we can do right now is put a notice on the home page.
