### ISSUE TITLE
User logs off but items in queue slowly tick away from saying queued to logged off

### ISSUE THREAD

**Issue by Climbatiz** [nicotine-plus/nicotine-plus#3209]
Nicotine+ version:  3.3.7rc1
Operating System/Distribution: Win10

### Describe the bug
As title says, user logs off but not all files that were in the queue are marked as Logged Off, but rather it slowly marks them as i guess client expects the transfer to start exept user has logged off and then marks that queued item as Logged Off, this is a common bug that has lasted for many Nicotine versions, just thought i'd report it since some dev here said we should report bugs ;}

### Additional context
No screens atm, if needed, can screeny it next time it happens

**Comment by mathiascode** [comment]
It's intentional behavior, to allow users to keep their queue position in a long queue if they reconnect.

If there are no other users in the queue, marking those uploads as "User logged off" should be fairly quick though. If there's a delay of a few seconds between each upload, it's probably a bug.
