### ISSUE TITLE
Can't download from certain users

### ISSUE THREAD

**Issue by iyra** [Nicotine-Plus/nicotine-plus#37]
Having followed the advice given in the documentation, I ensured that the port that Nicotine+ was operating on is open, and I tested it with several port-testing utilities, the result being that Nicotine+ should be able to work fine.

However I am simply unable to download from a large number of users. No error at all is reported, I simply click "download" on a file in the Downloads tab and nothing happens. With some users it works, but often I have to try 6 or 7 different users before finding one that I can download from.

I have uPnP disabled due to the fact that Nicotine+ complains about an "unknown exception" when loading uPnP. I am under the impression that I don't need uPnP to use the software.

The problem happens on both the version run from this current git repo, and on the Debian stable install.

I'm not sure if this counts as a bug or not, as this behaviour should be what happens when my ports are incorrectly configured. However there seems to be no such problem.

Thanks.

**Comment by iyra** [comment]
It seems that I'm unable to use uPnP at all with my current set-up. Is there still a way that I can download files from all users, without uPnP? I have "I can accept direct connections" enabled.

**Comment by gfarmerfr** [comment]
Hi @iyra,

I would recommend avoiding UPnP for the time being because it seems some bugs are still lurking around even if I've tried to fix some of them.

If you have "I can accept direct connections" enable you must also redirect the port Nicotine+ is listening on (usually 2234) on your router to your pc (port redirection also called port mapping). Something like your_public_ip:2234 => your_internal_pc_ip:2234.

Also there are some bugs i'll try to track down related to transfers that most likely were introduced a few years back just after the 1.2.16 release. I'll be on vacation next week and would have time to look into it.

**Comment by gfarmerfr** [comment]
@iyra 

I've a branch here https://github.com/gfarmerfr/nicotine-plus/tree/develop that might solved the download issue.
Could you test it and report back ?

Thx

**Comment by gfarmerfr** [comment]
Hi @iyra 

I had the same problem as you since ages but I think I managed to fixed it.
I've let my client run a few days and I didn't see any download/uploads getting stuck anymore.

I've pushed my branch on master (febf220) so it should solve the problem.

I'm closing this bug: please reopen it if you still have problems on current master.

**Comment by iyra** [comment]
Thank you for your work, I will be checking out the change soon and I'll re-open if I still have problems.
