### ISSUE TITLE
Sort by speed

### ISSUE THREAD

**Issue by hboetes** [nicotine-plus/nicotine-plus#373]
Could you sort search results by speed by default? :-) Or at least make clicking it sort decreasing instead of increasing? I always have to press that button twice.

slsk also sorts by speed by default.

Thanks!

**Comment by jasonsmedvik** [comment]
Does not this exist already? It seems I can click the Speed column and it sorts the results.

**Comment by mathiascode** [comment]
@jasonsmedvik It is possible to sort after you've searched for something, but this issue is about sorting every search by speed by default.

This feature request is currently blocked due to an issue where the scrollbar doesn't stay in place when you start scrolling before all the results have finished sorting. I'm not sure how to fix the issue.

**Comment by slook** [comment]
> at least make clicking it sort decreasing instead of increasing?

Flipping the order of the sort as suggested would close this issue adequately, since #2170 will handle default sorting.
