### ISSUE TITLE
1.4.0 - Hide Buddy List

### ISSUE THREAD

**Issue by ghost** [Nicotine-Plus/nicotine-plus#42]
Slackware 14.2 x86_64 with python-2.7.13, with nic+ 1.4.0 I noticed I can hide all the tabs except the ```Buddy List```.

When I right click ```Buddy List``` nothing appears like the other tabs. I see under the ```Modes``` that ```Buddy List``` is shown, so I'm assuming it should be able to be hidden as well...

THANKS

**Comment by gfarmerfr** [comment]
Hi @Geyup,

Yes it's not specific to 1.4.0 it was already the case in 1.2.16.
In fact when I switch from glade to gtkbuilder I stumble upon this part of the code and had seen that's it a "special" case of a notebook tab that can be switch around in the interface.

Technically it's feasible and I can add the menu to hide it but I'm not decided if we should do it.
I would like a little more feedback from the community on this before making a decision so I'll ask on the IRC chan what's their opinions on that.

**Comment by gfarmerfr** [comment]
I've looked at the actual code of the "special case" of the Buddy List. Frankly it's quite messy and adding the "Hide Tab" functionality would mean a bunch of code refactoring and lot of testing.
For example in the "View" menu you can choose where to put the buddy list but there's no way to hide it entirely since the 3 choices are in a RadioMenu and one of them must be selected...
 
I think that's out of scope for a stable bugfix release (1.4.1) so I'll tag this bug as an enhancement to be done for the next stable release (1.6).

**Comment by Geyup** [comment]
Seems odd that whoever coded this in the beginning didn't have the Buddy List hide like all the other tabs...

For me soulseek seems to have the best collection of music in a P2P app, but I don't care for the buddy and online community aspects of it, I just search and download and that's it...

Ok I'm a leecher LOL, so I like to hide all the crap I don't use...

THANKS

P.S. Speaking of removing everything, do you think it's possible to have just a simple search and download client of nicotine? I wonder if you created something like this, stripping out all the community related stuff, in the long run it makes for a simpler client to maintain?

Hmm

**Comment by gfarmerfr** [comment]
From what i can gather from the git log the buddylist thing was touched a third position option in 2008 via this commit 6bc70894547f08e990a2e47efc1614af23cebf8d before that it was already a special case but the git log doesn't go back futher than the svn rebuild in 2006. So yes it's a special case since a very long time :).

I haven't create a stripped down client sorry but I think @Mutnick was speaking of something of that sort some times ago. Not sure about the details though.

**Comment by Geyup** [comment]
Hide list and stripped version, ok...

thanks
