### ISSUE TITLE
Question; what diff between scanning and rebuilding share ?

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#430]
so what is the real diff between both of them for myself i m using nic+ since first launch and 
1/ i never understand why two options for that 
2/ im using only scanning and it does what it suppose to do 
i can see you made different improvement for UI deleting or adding and moving  features so maybe can you consider those two options new way to scan share ?

thank you

**Comment by mathiascode** [comment]
Seems like scanning reuses the old database, and only adds new files/folders found since the last scan, while rebuilding adds every file again. I'm not sure when you would need to manually rebuild the database, since Nicotine+ already does that if a rescan goes wrong. We can probably remove the rebuild menu item.
