### ISSUE TITLE
a separate program for database scanning

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#443]
Would it be possible to have a separate program for database scanning?

This has the benefit the database scanner can be called from the CLI:
- to create cron jobs.
- to check the output for errors.
- to be able to restart nicotine without interrupting the scanning process.
- reduce load on front-end process

Another solution might be to add CLI options to nicotine.

**Comment by mathiascode** [comment]
This would ideally be done by separating the whole scanning process into a new subprocess (with the multiprocessing module), and adding a CLI flag to start the scanning process separately from the rest of the program. I'd like to avoid creating completely new programs, mainly to avoid a situation like the Museek+ project, which is a nightmare to get started on (from both a user and a developer's perspective) and maintain due to the amount of abandoned junk included in the repository.

**Comment by hboetes** [comment]
The current code is working so well I think we can drop this issue. I'm perfectly fine with closing it.
