### ISSUE TITLE
send to player does not work.

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#53]
Hello im using nic+ from today it looks like send to player option does not work 
im using ubuntu 16.10 with default player Rhythmbox

Double clicking options are activated to "send to player" both up/dl but does not send to player.
no log or debug info in log aera .

when activate "open directory" nautilus starts and open folder with good place

thank you best regards

**Comment by zniavre** [comment]
good morning 

So i investigate more and i hav found that this option is missing mpris or rhythmbox option  (like now playing is missing RB too) so i just added "rhythmbox $" to send to player aera

![capture du 2017-03-16 08-56-07](https://cloud.githubusercontent.com/assets/2409578/23986845/8e5b63bc-0a26-11e7-9d45-49e813aba332.png)

it works now ...  sorry for disturbing

**Comment by gfarmerfr** [comment]
Hi @zniavre,

Sorry for the late response.
I've added "rhythmbox $" to the default list of player for 1.4.2.

To make now playing works with rhythmbox you shoul use the MPRIS(v2) option on the nicotine+ side and check that the corresponding MPRIS plugin is activated in rhythmbox and it should work.
the old "Rhythmbox" option of nowplaying was removed via this commit efd1ee1 because since some times now (I think sine Rhythmbox 3) some endpoints of the rhythmbox dbus interface were removed in favor of the MPRIS dbus interface.
