### ISSUE TITLE
Let user choose for International flag

### ISSUE THREAD

**Issue by Kawsay** [Nicotine-Plus/nicotine-plus#569]
I'd like to be able to go in **Edit** > **Settings**, and inside the **Misc** category find a "**Flag**" (or "**GeoIP**") category that allow me to select an international flag* by ticking a checkbox.

Distance may be useful for selecting peers, though I think it should be dissociated from national flags.

Thanks for your amazing work,
warm regards

_____
\* example of international flag from chess.com (centred in Europe) ![image](https://user-images.githubusercontent.com/44816995/90660430-2f74e700-e246-11ea-98cf-eb4f724a718d.png)

**Comment by hboetes** [comment]
I appreciate your sentiment on the matter and I think this world is far too nationalized indeed. But in practical terms this is not how it works. You could modify your own flag easily enough by changing the flag of your country, but nobody would see it since you only modify how _your client_ perceives where you come from and nobody else would notice it. That would require you to change your IP, and that you cannot do, unless you'd use a VPN, which would simply result in having another country flag and a slower connection.

**Comment by Kawsay** [comment]
Thanks for your answer and for proposing alternatives. It was indeed quite a naïve suggestion, as I don't understand how GeoIP works and is integrated inside Nicotine.

Have fun coding !
