### ISSUE TITLE
Add file type (e.g. FLAC) to available filters

### ISSUE THREAD

**Issue by kiplingw** [Nicotine-Plus/nicotine-plus#677]
It would be wonderful if there was a way to search for music with the results limited to a specific format, like lossless formats only (e.g. FLAC).

**Comment by mathiascode** [comment]
I suppose a separate filter would be more user-friendly though. If someone wants to implement it, I would gladly accept it.

**Comment by alekksander** [comment]
would be nice to have extra specified hardcoded filter with format name, but isn't it doable quite easily with simply adding „flac” at the end of searched phrase? also filtering in→„flac” works for me. To see all lossless filter out→„mp3”, or set bitrate filter above 320kbps.

**Comment by redactedscribe** [comment]
I think it should be documented rather than implemented as a further field as I believe this field wouldn't have any special means for determining a FLAC file compared to the current file name filtering that is possible (though, the field could use regex such as `.+\.flac$` by default, for accuracy that normal users may not know how to achieve).

Tooltips directly on the filter fields could go a long way to educate without needing to resort to the help file, or a newly included filter field: Include: `Examples: "mp3", "pdf", or the regular expression ".+\.(flac|wav)$".`, Exclude: `Examples: "txt", "exe", or the regular expression ".+\.jpe?g$".`.

**Comment by kiplingw** [comment]
I think asking most lay users to provide a regular expression is not practical. But allowing it I certaintly can't see anything wrong with it. 

One way to solve this is to have a button or checkbox, _Lossless only_, that when selected automatically implicitly supplies the case insensitive regular expression (initially the string need not be visible) for FLAC, WAV (technically not "lossless" in the sense that it isn't compressed, but whatever), ALAC, APE, WavPack, etc. 

This will miss the minority of cases where we can't tell from the extension, such as certain containers what's actually in them that can contain either lossly or lossless. But it will be a heuristic that's right most of the time.

**Comment by redactedscribe** [comment]
> I think asking most lay users to provide a regular expression is not practical. But allowing it I certaintly can't see anything wrong with it.

Regex is actually already possible via a preferences option.


Some things I've noticed as tested the state of searching and filtering: In the case of FLAC, just filtering by the term alone will return you ~95% accurate results (which I'd argue is practical enough for the average user; just search "music" and try it), and similar accuracy for other file types such as "wav", and even higher for "wavpack" and other non-words. It makes the addition of a new dedicated field just for a minor increase in accuracy hard to justify in my eyes. I imagine those who only want files ending in `.flac` would be likely motivated enough to write out the regex / copy an example / read the help.

There is a concern for how to fit all the filter fields in when adding a new one, this is the reason behind trying to justify the fields as they already are. I do think it'd be more convenient, as you imply, though.

Going along with this thinking, other approaches could be a checkbox next to the Result Filters button that limits matches to filenames only (filters currently also matches folders). Or to not omit `.` from filter terms i.e. `.flac` (stripping the dot is only needed for _network searches_ I believe, due to how some clients respond to unexpected characters. Maybe the filter is using the same code and stripping dots unnecessarily?). The filter could also support quotation, for precision without needed to use regex i.e. `".flac"`. Another alternative is to provide a new column "Filetype" which would make browsing the results for a filter of `flac` contiguous (if grouping mode is "Ungrouped").

There seems to be a few options that wouldn't involve another field, but yes, they aren't as simple, but hopefully not unreasonable at the same time.

**Comment by mathiascode** [comment]
A file type field fits in rather nicely now that the labels for the fields are removed, so I decided to implement at the same time as #946.

**Comment by kiplingw** [comment]
I think a simple checkbox next to the search field, _Lossless only_, solves the problem for the average lay user.

**Comment by mathiascode** [comment]
> I think a simple checkbox next to the search field, _Lossless only_, solves the problem for the average lay user.

The idea is good, but I feel this is a bit too specific and inflexible for my taste. Assuming that people who are into lossless music have some knowledge of which formats to look for, I think it's better to have a file type combobox with a few preset options in the dropdown menu, giving us the opportunity to also hint at non-audio content available on Soulseek.

**Comment by kiplingw** [comment]
I think that sounds like a plan. Although I am a bit reluctant to facilitate non-audio content since the protocol and the network as a whole originally weren't really designed for that.

**Comment by mathiascode** [comment]
> I think that sounds like a plan. Although I am a bit reluctant to facilitate non-audio content since the protocol and the network as a whole originally weren't really designed for that.

We can limit the default filters to audio content, perhaps also jpg/jpeg for album artwork (personally I find this useful for looking up higher quality cover art or liner notes for rare releases).

**Comment by kiplingw** [comment]
I suggest leaving it strictly to audio as a default, but then perhaps having an option in the settings to augment it with those kinds of things.
