### ISSUE TITLE
Please Help - Columns Position Not Being Maintained

### ISSUE THREAD

**Issue by ghost** [Nicotine-Plus/nicotine-plus#8]
Hello,

If anyone sees this and can just enable this request, this would be great! I'm using the latest version...

For me the application is working fine, except for the `Columns` positions are not being maintained.

The `Downloads, Uploads` sections, when opening and closing nicotine the positions are not maintained after you move them. And the `Search Files` section loosses the position everytime you do a new search.

Please see the attached screen shot below, you'll notice some of the `Columns`  are bunched together in the `Downloads` section with the words cut off.

I find this such a pain in the butt, especially with the `Search Files` section needing them moved everytime you do a new search, and not just maintaining position.

This constant need of moving the columns has me ready to toss this app to the trash, but if someone could fix this issue, it would really make using nicotine+ enjoyable. I can't believe for how much development had gone on with this application, the columns were never made to maintain position, hmm...

Maybe this works on some desktops and window managers, I'm using Openbox and Openbox doesn't maintain something like this...

Thank you very much for those that look at this issue/request, and consider it!

Happy New Year!

![nicotine](https://cloud.githubusercontent.com/assets/13072581/12073142/48d7760e-b104-11e5-88bd-b9de768d1aef.jpg)

**Comment by Geyup** [comment]
Something else I forgot to mention, under the ```Search Files``` after you've performed a search and the columns appear, you can right click on them and get a popup to uncheck ones you don't want to see, but when doing a new search, they just reappear.

It would be great to also have these stay hidden.

thank you again...

**Comment by Geyup** [comment]
I'm at a loss to understand how such a project could die! What could be better than this for music, is what I'd like to know?

Seriously, there is no one to fix some issues in this thing, especially at least these columns to make this more functional?

**Comment by gfarmerfr** [comment]
Hi @Geyup 

I've decided to work on n+, so there is someone now :)

Thought I've a lot on my plate at this time and this is a long standing bug I agree with you: the constant need to fiddle around the GUI is a royal pain.

**Comment by Geyup** [comment]
@gfarmerfr 

Oh YEAH someone is here!

This is amazing, I'll try not to pee my pants LOL...

Yes it's a real royal pain in the arse!

I hope you'll have time soon to work on this, and if you need someone testing it it to see how it works, I'll be sure to keep an eye on this post.

Thank you very much gfarmerfr for taking this on, it's greatly appreciated!

nicotine-plus is an awesome application, I hope you will be able to carry it forward for many years to come, it really needs someone!

**Comment by Geyup** [comment]
WOW you're really going at it, this is great!

Can't wait to try it out when ready to do some testing.

Keep up the great work gfarmerfr!

**Comment by gfarmerfr** [comment]
Thx for the support :)

I've been in holidays since 3 weeks until the end of this one so this explain the amount of commits :smile: 

For the time being i'm doing high level infrastructural cleanup: cleaning up dependencies, get through the backlog of patches from distros, rebuilding the packaging/installation part, cleaning up the wiki & old bugtracker, document most of the things I've leaned and some little easy fixes here and there. While doing this I'm learning how the code base works.

Basically I'm cleaning up the short term goals of the [TODO](https://github.com/eLvErDe/nicotine-plus/blob/master/doc/TODO.md). It's necessary because if we don't, someday soon distributions might dump us because we depend on old unmaintained packages.

As soon as the short terms goals are cleared I will release a 1.3.0-rc1.
From the remaining items list a my guess is somewhere around the end of the year.
For info what distro/OS are you using ?

So maybe this bug might do it if it doesn't require changing the whole UI for list views :)

**Comment by Geyup** [comment]
Sounds great!

I'm running Slackware

**Comment by Geyup** [comment]
@ gfarmerfr was this worked on for 1.4.0? 

Because in 1.4.0 they are still not being maintained, you have to keep moving them around...

THANKS

**Comment by Geyup** [comment]
Hi gfarmerfr, something I noticed in 1.4.1 s when you uncheck to remove some sections in the columns for the Downloads sections, when you close and reopen nicotine these reappear...

Oh I don't mean to be a pain, not sure if you have anything as priority you have to do next, but I really hope all this column stuff can be fixed soon?

Thanks for bringing nicotine back to life! Keep up the great work! :)

:+1:

**Comment by gfarmerfr** [comment]
Hi @Geyup 

I've just look at it and was due to a namespace conflict in the config file introduced quite a long time ago via this commit https://github.com/Nicotine-Plus/nicotine-plus/commit/2bdfe9d36e1f7085d49c3aff9c66049c71c01e14
I've pushed the fix on master and on the 1.4 branch for a future 1.4.2.

I'll try to fix the columns positions issue for 1.6 if I've time.
Converting the nicotine custom (very hackish) config format to a json file (in the TODO list) would help quite bit though.

**Comment by Geyup** [comment]
Thanks gfarmerfr :+1:

**Comment by sla0101** [comment]
Hi how'a this coming along?

Looks like things have slowed down? :(

**Comment by Geyup** [comment]
@gfarmerfr are you still around and doing ok?

I don't see anything going on for a long time, I thought you'd still be hacking away... :(

**Comment by Geyup** [comment]
Oh I'm sad, it's coming up almost 2 years since I posted this, I can't believe it's been that long.

I hope you are doing ok gfarmerfr, and maybe you just have a life is all.... LOL

Maybe one day this can be fixed...

**Comment by Geyup** [comment]
@gfarmerfr hello are you still around?

Thanks

**Comment by Geyup** [comment]
Hi,

Is there anyone around that is reading this, that has the coding skills to fix this?

This issue has always existed, and I was happy when I saw gfarmerfr reply, thinking this would of been fixed by now...

Thanks

**Comment by Mutnick** [comment]
@Geyup I should have time to look at it this weekend. I think saving and restoring the column widths could be trivial to implement.  Do you also re-arrange the order of columns?

**Comment by Geyup** [comment]
@Mutnick, hi, well it's been a long time since I've used nicotine, and last I remember, all I did was uncheck sections I don't use, that's all.

So as to re-arrange, move them around? No I don't do this.

This is AMAZING if this can finally be fixed, I'm surprised more people haven't been talking about this. To me this is the #1 problem for me about this app...

THANKS

**Comment by Mutnick** [comment]
Implemented an initial fix for this. The initial requester has ghosted and anyone trying out this functionality is welcome to leave feedback.

**Comment by zniavre** [comment]
im tryng right now, even if i do not understand the colums bug and do not see really which improvements came with it , nicotine+ still working great and this is THE point for me ...   :o)  

thank you for fix ... 
><((((*>

**Comment by 0pLuS0** [comment]
@Mutnick I tested this and I see the same problems...

For now I only tested one section ```Search files```.

I unchecked two columns, ```Country``` and ```Directory```, now when restarting I see ```Directory``` will always return, but the columns seem to be staying in the same place, but hard to tell since ```Directory``` keeps returning, and it appears to move the columns a little.

Also something else I noticed, if I hide a few tabs like ```Chat rooms``` and ```Buddy List```, when I start nicotine for the first time it opens up on the last tab on the right. If I don't hide any tabs nicotine always opens under ```Chat rooms``` on the left. It would be nice to have nicotine open up on the tab you left it at when you closed it, or an option if not much trouble in the ```Settings``` to choose to open on the last tab used, or default to the far left... I find this odd, that I hide tabs and it changes from opening up on the far left, to then the far right... hmm

thanks

**Comment by MarkoIndaco** [comment]
I guys, I add myself to the list. I have the exact problem mentioned in the title post. If can help I'm on Linux Mint 18.2 (Cinnamon - 64bit). I'm new with Linux so every suggest are pretty appreciated.
Thank you in advance

**Comment by 0pLuS0** [comment]
I have all the same problems, so let's not worry about the Ghost.

I just hope Mutnick doesn't have to much of a life, and we can get this fixed...

I too have wished for this all to be fixed, using Nicotine, always have to adjust it is not pleasant.

**Comment by MarkoIndaco** [comment]
Yeah i got it. I was thinking for something like "run a little script" every Nicotine starts, but I have no skills to writing code. It would be possibile something like that?

**Comment by 0pLuS0** [comment]
No script, the code needs bugs worked out of it.

@Mutnick hello... :)

**Comment by 0pLuS0** [comment]
@Mutnick hello, did you see my reply? 

There's still some issues...

Thanks

**Comment by 0pLuS0** [comment]
@Mutnick hello, are you still out there? 

We need you!

I still have problems with this, I hope you can please fix?

Thank you

**Comment by 0pLuS0** [comment]
@Mutnick found another issue in the ```Downloads``` section, ```Path``` keeps returning when I uncheck it...

**Comment by 0pLuS0** [comment]
@Mutnick all this time I forgot to mention, the problems with the Columns is not an ```Enhancement``` the Columns have a  ```Bug``` with not maintaining position, and sections returning when unchecked...

I hope you will have time to work on this, because everytime closing and reopening nicotine, you always have to reposition everything over...

Thanks
