### ISSUE TITLE
Uploads not working

### ISSUE THREAD

**Issue by march-hare1** [Nicotine-Plus/nicotine-plus#85]
Hi!  Unlike others who have commented, I don't have the issue of Uploads folders not getting recognized that I can see, it's just a matter of Nicotine+ 1.4.2 on Linux Mint 19 64-bit I uploaded from the PPA as not showing that I am not sharing.  I was just informed by someone I was downloading from and I look like a JERK because of it. Anyone have any suggestions on how to fix this situation? Thanks!

**Comment by oknozor** [comment]
Hello @march-hare1, I got exactly the same problem with nicotine `1.4.1-4` on arch. 

Maybe you could check permissions on your shared folder just in case. You could also check if your shared folder is on a mounted device with correct permissions (usb, sdcard). 

I don't think it's a permission issue in my case since i've got the following rights on my music directory : `drwxr-xr-- 82 okno okno 4.0K Dec 12 09:02 Music`. 
Also my music directory is on a sdcard mounted via fstab with the following options : 

```
# SD CARD data
UUID=f7e4b690-7780-49d9-9199-514caf867412   /mnt/data   auto        defaults,noatime,auto,nofail 0 2
```

Also, nicotine+ seems to be scanning the files inside that directory (I see them in the progress bar during the scan) but after the scan complete the upload section ends up empty. 

Any help would be welcome, we just want to share some music :notes: !

**Comment by mathiascode** [comment]
Is this still an issue on the master branch?

**Comment by march-hare1** [comment]
No, it was a permissions issue on my side. Sorry for leaving this open. xoxo!
