### ISSUE TITLE
Nicotine v2.2.0 immediately crashes on startup on Windows 10 v19042.630

### ISSUE THREAD

**Issue by vctls** [Nicotine-Plus/nicotine-plus#893]
Nicotine+ version:  v2.2.0
Operating System/Distribution:
Windows 10 v19042.630

### Describe the bug
Nicotine+ v2.2.0 process immediately crashes. Main window doesn't event appear

### Expected behavior
Nicotine+ window appears

### Steps to reproduce the bug
Install, try to run.

### Additional context
Tried rebooting, removing both program and user folder, excluding program folder from MsMpEng.
Not sure if relevant but my main Python install is v3.9.0
Version 2.1.2 works fine.
I'll try obtaining logs.

**Comment by mathiascode** [comment]
Is your system set to another language than English? Could be an issue with the translations again.

**Comment by vctls** [comment]
Yes, it's in French. And actually, I'd rather have Nicotine+ in English. But I don't see the option to change the language…

**Comment by vctls** [comment]
I just switched my Windows to English and yes, now it's working fine.
Still can't find the option in Nicotine+ though. Is there one?

**Comment by mathiascode** [comment]
Could you change the language back to French, and check if this build launches, and translations still work fine? http://a.tmp.ninja/5c0tqoTunGn3.zip

There used to be an option to change the language years ago, but it was apparently removed due to complications. Perhaps I could look into it at some point, if I have extra time. (thanks :) )

**Comment by vctls** [comment]
Yep, your patched version works.
